// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/linear_solver/linear_solver.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.linearsolver;

public interface MPSolveInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.MPSolveInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * How much wall time (resp. user time) elapsed during the Solve() of the
   * underlying solver library. "wall" time and "user" time are to be
   * interpreted like for the "time" command in bash (see "help time").
   * In particular, "user time" is CPU time and can be greater than wall time
   * when using several threads.
   * </pre>
   *
   * <code>optional double solve_wall_time_seconds = 1;</code>
   * @return Whether the solveWallTimeSeconds field is set.
   */
  boolean hasSolveWallTimeSeconds();
  /**
   * <pre>
   * How much wall time (resp. user time) elapsed during the Solve() of the
   * underlying solver library. "wall" time and "user" time are to be
   * interpreted like for the "time" command in bash (see "help time").
   * In particular, "user time" is CPU time and can be greater than wall time
   * when using several threads.
   * </pre>
   *
   * <code>optional double solve_wall_time_seconds = 1;</code>
   * @return The solveWallTimeSeconds.
   */
  double getSolveWallTimeSeconds();

  /**
   * <code>optional double solve_user_time_seconds = 2;</code>
   * @return Whether the solveUserTimeSeconds field is set.
   */
  boolean hasSolveUserTimeSeconds();
  /**
   * <code>optional double solve_user_time_seconds = 2;</code>
   * @return The solveUserTimeSeconds.
   */
  double getSolveUserTimeSeconds();
}
