// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/util/int128.proto
// Protobuf Java Version: 4.26.1

package com.google.ortools.util;

public final class Int128OuterClass {
  private Int128OuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Int128OuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_Int128_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_operations_research_Int128_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ortools/util/int128.proto\022\023operations_" +
      "research\"#\n\006Int128\022\014\n\004high\030\001 \001(\003\022\013\n\003low\030" +
      "\002 \001(\004B1\n\027com.google.ortools.utilP\001\252\002\023Goo" +
      "gle.OrTools.Utilb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_operations_research_Int128_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_operations_research_Int128_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_operations_research_Int128_descriptor,
        new java.lang.String[] { "High", "Low", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
