// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/pdlp/solvers.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.pdlp;

public interface MalitskyPockParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.pdlp.MalitskyPockParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * At every inner iteration the algorithm can decide to accept the step size
   * or to update it to step_size = step_size_downscaling_factor * step_size.
   * This parameter should lie between 0 and 1. The default is the value used in
   * Malitsky and Pock (2016).
   * </pre>
   *
   * <code>optional double step_size_downscaling_factor = 1 [default = 0.7];</code>
   * @return Whether the stepSizeDownscalingFactor field is set.
   */
  boolean hasStepSizeDownscalingFactor();
  /**
   * <pre>
   * At every inner iteration the algorithm can decide to accept the step size
   * or to update it to step_size = step_size_downscaling_factor * step_size.
   * This parameter should lie between 0 and 1. The default is the value used in
   * Malitsky and Pock (2016).
   * </pre>
   *
   * <code>optional double step_size_downscaling_factor = 1 [default = 0.7];</code>
   * @return The stepSizeDownscalingFactor.
   */
  double getStepSizeDownscalingFactor();

  /**
   * <pre>
   * Contraction factor used in the linesearch condition of Malitsky and Pock.
   * A step size is accepted if primal_weight * primal_stepsize *
   * norm(constraint_matrix' * (next_dual - current_dual)) is less
   * than linesearch_contraction_factor * norm(next_dual - current_dual).
   * The default is the value used in Malitsky and Pock (2016).
   * </pre>
   *
   * <code>optional double linesearch_contraction_factor = 2 [default = 0.99];</code>
   * @return Whether the linesearchContractionFactor field is set.
   */
  boolean hasLinesearchContractionFactor();
  /**
   * <pre>
   * Contraction factor used in the linesearch condition of Malitsky and Pock.
   * A step size is accepted if primal_weight * primal_stepsize *
   * norm(constraint_matrix' * (next_dual - current_dual)) is less
   * than linesearch_contraction_factor * norm(next_dual - current_dual).
   * The default is the value used in Malitsky and Pock (2016).
   * </pre>
   *
   * <code>optional double linesearch_contraction_factor = 2 [default = 0.99];</code>
   * @return The linesearchContractionFactor.
   */
  double getLinesearchContractionFactor();

  /**
   * <pre>
   * Malitsky and Pock linesearch rule permits an arbitrary choice of the first
   * step size guess within an interval [m, M]. This parameter determines where
   * in that interval to pick the step size. In particular, the next stepsize is
   * given by m + step_size_interpolation*(M - m). The default is the value used
   * in Malitsky and Pock (2016).
   * </pre>
   *
   * <code>optional double step_size_interpolation = 3 [default = 1];</code>
   * @return Whether the stepSizeInterpolation field is set.
   */
  boolean hasStepSizeInterpolation();
  /**
   * <pre>
   * Malitsky and Pock linesearch rule permits an arbitrary choice of the first
   * step size guess within an interval [m, M]. This parameter determines where
   * in that interval to pick the step size. In particular, the next stepsize is
   * given by m + step_size_interpolation*(M - m). The default is the value used
   * in Malitsky and Pock (2016).
   * </pre>
   *
   * <code>optional double step_size_interpolation = 3 [default = 1];</code>
   * @return The stepSizeInterpolation.
   */
  double getStepSizeInterpolation();
}
