// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/pdlp/solve_log.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.pdlp;

/**
 * <pre>
 * Identifies the type of point used to compute the fields in a given proto; see
 * ConvergenceInformation and InfeasibilityInformation.
 * </pre>
 *
 * Protobuf enum {@code operations_research.pdlp.PointType}
 */
public enum PointType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>POINT_TYPE_UNSPECIFIED = 0;</code>
   */
  POINT_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * Current iterate (x_k, y_k).
   * </pre>
   *
   * <code>POINT_TYPE_CURRENT_ITERATE = 1;</code>
   */
  POINT_TYPE_CURRENT_ITERATE(1),
  /**
   * <pre>
   * Difference of iterates (x_{k+1} - x_k, y_{k+1} - y_k).
   * </pre>
   *
   * <code>POINT_TYPE_ITERATE_DIFFERENCE = 2;</code>
   */
  POINT_TYPE_ITERATE_DIFFERENCE(2),
  /**
   * <pre>
   * Average of iterates since the last restart.
   * </pre>
   *
   * <code>POINT_TYPE_AVERAGE_ITERATE = 3;</code>
   */
  POINT_TYPE_AVERAGE_ITERATE(3),
  /**
   * <pre>
   * There is no corresponding point.
   * </pre>
   *
   * <code>POINT_TYPE_NONE = 4;</code>
   */
  POINT_TYPE_NONE(4),
  /**
   * <pre>
   * Output of presolver.
   * </pre>
   *
   * <code>POINT_TYPE_PRESOLVER_SOLUTION = 5;</code>
   */
  POINT_TYPE_PRESOLVER_SOLUTION(5),
  /**
   * <pre>
   * Combined solution from primal and dual feasibility polishing.
   * </pre>
   *
   * <code>POINT_TYPE_FEASIBILITY_POLISHING_SOLUTION = 6;</code>
   */
  POINT_TYPE_FEASIBILITY_POLISHING_SOLUTION(6),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      PointType.class.getName());
  }
  /**
   * <code>POINT_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int POINT_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Current iterate (x_k, y_k).
   * </pre>
   *
   * <code>POINT_TYPE_CURRENT_ITERATE = 1;</code>
   */
  public static final int POINT_TYPE_CURRENT_ITERATE_VALUE = 1;
  /**
   * <pre>
   * Difference of iterates (x_{k+1} - x_k, y_{k+1} - y_k).
   * </pre>
   *
   * <code>POINT_TYPE_ITERATE_DIFFERENCE = 2;</code>
   */
  public static final int POINT_TYPE_ITERATE_DIFFERENCE_VALUE = 2;
  /**
   * <pre>
   * Average of iterates since the last restart.
   * </pre>
   *
   * <code>POINT_TYPE_AVERAGE_ITERATE = 3;</code>
   */
  public static final int POINT_TYPE_AVERAGE_ITERATE_VALUE = 3;
  /**
   * <pre>
   * There is no corresponding point.
   * </pre>
   *
   * <code>POINT_TYPE_NONE = 4;</code>
   */
  public static final int POINT_TYPE_NONE_VALUE = 4;
  /**
   * <pre>
   * Output of presolver.
   * </pre>
   *
   * <code>POINT_TYPE_PRESOLVER_SOLUTION = 5;</code>
   */
  public static final int POINT_TYPE_PRESOLVER_SOLUTION_VALUE = 5;
  /**
   * <pre>
   * Combined solution from primal and dual feasibility polishing.
   * </pre>
   *
   * <code>POINT_TYPE_FEASIBILITY_POLISHING_SOLUTION = 6;</code>
   */
  public static final int POINT_TYPE_FEASIBILITY_POLISHING_SOLUTION_VALUE = 6;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PointType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PointType forNumber(int value) {
    switch (value) {
      case 0: return POINT_TYPE_UNSPECIFIED;
      case 1: return POINT_TYPE_CURRENT_ITERATE;
      case 2: return POINT_TYPE_ITERATE_DIFFERENCE;
      case 3: return POINT_TYPE_AVERAGE_ITERATE;
      case 4: return POINT_TYPE_NONE;
      case 5: return POINT_TYPE_PRESOLVER_SOLUTION;
      case 6: return POINT_TYPE_FEASIBILITY_POLISHING_SOLUTION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PointType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PointType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PointType>() {
          public PointType findValueByNumber(int number) {
            return PointType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.ortools.pdlp.SolveLogOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final PointType[] VALUES = values();

  public static PointType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PointType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:operations_research.pdlp.PointType)
}

