// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/pdlp/solve_log.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.pdlp;

/**
 * <pre>
 * Specifies whether a restart was performed on a given iteration.
 * </pre>
 *
 * Protobuf enum {@code operations_research.pdlp.RestartChoice}
 */
public enum RestartChoice
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RESTART_CHOICE_UNSPECIFIED = 0;</code>
   */
  RESTART_CHOICE_UNSPECIFIED(0),
  /**
   * <pre>
   * No restart on this iteration.
   * </pre>
   *
   * <code>RESTART_CHOICE_NO_RESTART = 1;</code>
   */
  RESTART_CHOICE_NO_RESTART(1),
  /**
   * <pre>
   * The weighted average of iterates is cleared and reset to the current point.
   * Note that from a mathematical perspective this can be equivalently viewed
   * as restarting the algorithm but picking the restart point to be the current
   * iterate.
   * </pre>
   *
   * <code>RESTART_CHOICE_WEIGHTED_AVERAGE_RESET = 2;</code>
   */
  RESTART_CHOICE_WEIGHTED_AVERAGE_RESET(2),
  /**
   * <pre>
   * The algorithm is restarted at the average of iterates since the last
   * restart.
   * </pre>
   *
   * <code>RESTART_CHOICE_RESTART_TO_AVERAGE = 3;</code>
   */
  RESTART_CHOICE_RESTART_TO_AVERAGE(3),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RestartChoice.class.getName());
  }
  /**
   * <code>RESTART_CHOICE_UNSPECIFIED = 0;</code>
   */
  public static final int RESTART_CHOICE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * No restart on this iteration.
   * </pre>
   *
   * <code>RESTART_CHOICE_NO_RESTART = 1;</code>
   */
  public static final int RESTART_CHOICE_NO_RESTART_VALUE = 1;
  /**
   * <pre>
   * The weighted average of iterates is cleared and reset to the current point.
   * Note that from a mathematical perspective this can be equivalently viewed
   * as restarting the algorithm but picking the restart point to be the current
   * iterate.
   * </pre>
   *
   * <code>RESTART_CHOICE_WEIGHTED_AVERAGE_RESET = 2;</code>
   */
  public static final int RESTART_CHOICE_WEIGHTED_AVERAGE_RESET_VALUE = 2;
  /**
   * <pre>
   * The algorithm is restarted at the average of iterates since the last
   * restart.
   * </pre>
   *
   * <code>RESTART_CHOICE_RESTART_TO_AVERAGE = 3;</code>
   */
  public static final int RESTART_CHOICE_RESTART_TO_AVERAGE_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RestartChoice valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RestartChoice forNumber(int value) {
    switch (value) {
      case 0: return RESTART_CHOICE_UNSPECIFIED;
      case 1: return RESTART_CHOICE_NO_RESTART;
      case 2: return RESTART_CHOICE_WEIGHTED_AVERAGE_RESET;
      case 3: return RESTART_CHOICE_RESTART_TO_AVERAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RestartChoice>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RestartChoice> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RestartChoice>() {
          public RestartChoice findValueByNumber(int number) {
            return RestartChoice.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.ortools.pdlp.SolveLogOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final RestartChoice[] VALUES = values();

  public static RestartChoice valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RestartChoice(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:operations_research.pdlp.RestartChoice)
}

