// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/sat/cp_model.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.sat;

public interface CumulativeConstraintProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.sat.CumulativeConstraintProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.operations_research.sat.LinearExpressionProto capacity = 1;</code>
   * @return Whether the capacity field is set.
   */
  boolean hasCapacity();
  /**
   * <code>.operations_research.sat.LinearExpressionProto capacity = 1;</code>
   * @return The capacity.
   */
  com.google.ortools.sat.LinearExpressionProto getCapacity();
  /**
   * <code>.operations_research.sat.LinearExpressionProto capacity = 1;</code>
   */
  com.google.ortools.sat.LinearExpressionProtoOrBuilder getCapacityOrBuilder();

  /**
   * <code>repeated int32 intervals = 2;</code>
   * @return A list containing the intervals.
   */
  java.util.List<java.lang.Integer> getIntervalsList();
  /**
   * <code>repeated int32 intervals = 2;</code>
   * @return The count of intervals.
   */
  int getIntervalsCount();
  /**
   * <code>repeated int32 intervals = 2;</code>
   * @param index The index of the element to return.
   * @return The intervals at the given index.
   */
  int getIntervals(int index);

  /**
   * <pre>
   * Same size as intervals.
   * </pre>
   *
   * <code>repeated .operations_research.sat.LinearExpressionProto demands = 3;</code>
   */
  java.util.List<com.google.ortools.sat.LinearExpressionProto> 
      getDemandsList();
  /**
   * <pre>
   * Same size as intervals.
   * </pre>
   *
   * <code>repeated .operations_research.sat.LinearExpressionProto demands = 3;</code>
   */
  com.google.ortools.sat.LinearExpressionProto getDemands(int index);
  /**
   * <pre>
   * Same size as intervals.
   * </pre>
   *
   * <code>repeated .operations_research.sat.LinearExpressionProto demands = 3;</code>
   */
  int getDemandsCount();
  /**
   * <pre>
   * Same size as intervals.
   * </pre>
   *
   * <code>repeated .operations_research.sat.LinearExpressionProto demands = 3;</code>
   */
  java.util.List<? extends com.google.ortools.sat.LinearExpressionProtoOrBuilder> 
      getDemandsOrBuilderList();
  /**
   * <pre>
   * Same size as intervals.
   * </pre>
   *
   * <code>repeated .operations_research.sat.LinearExpressionProto demands = 3;</code>
   */
  com.google.ortools.sat.LinearExpressionProtoOrBuilder getDemandsOrBuilder(
      int index);
}
