/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.sat;

public class mainJNI {
  public final static native void delete_SolutionCallback(long jarg1);
  public final static native void SolutionCallback_onSolutionCallback(long jarg1, SolutionCallback jarg1_);
  public final static native long SolutionCallback_numBooleans(long jarg1, SolutionCallback jarg1_);
  public final static native long SolutionCallback_numBranches(long jarg1, SolutionCallback jarg1_);
  public final static native long SolutionCallback_numConflicts(long jarg1, SolutionCallback jarg1_);
  public final static native long SolutionCallback_numBinaryPropagations(long jarg1, SolutionCallback jarg1_);
  public final static native long SolutionCallback_numIntegerPropagations(long jarg1, SolutionCallback jarg1_);
  public final static native double SolutionCallback_wallTime(long jarg1, SolutionCallback jarg1_);
  public final static native double SolutionCallback_userTime(long jarg1, SolutionCallback jarg1_);
  public final static native double SolutionCallback_objectiveValue(long jarg1, SolutionCallback jarg1_);
  public final static native double SolutionCallback_bestObjectiveBound(long jarg1, SolutionCallback jarg1_);
  public final static native long SolutionCallback_solutionIntegerValue(long jarg1, SolutionCallback jarg1_, int jarg2);
  public final static native boolean SolutionCallback_solutionBooleanValue(long jarg1, SolutionCallback jarg1_, int jarg2);
  public final static native void SolutionCallback_stopSearch(long jarg1, SolutionCallback jarg1_);
  public final static native long new_SolutionCallback();
  public final static native void SolutionCallback_director_connect(SolutionCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void SolutionCallback_change_ownership(SolutionCallback obj, long cptr, boolean take_or_release);
  public final static native void SolveWrapper_setParameters(long jarg1, SolveWrapper jarg1_, byte[] jarg2);
  public final static native void SolveWrapper_addSolutionCallback(long jarg1, SolveWrapper jarg1_, long jarg2, SolutionCallback jarg2_);
  public final static native void SolveWrapper_clearSolutionCallback(long jarg1, SolveWrapper jarg1_, long jarg2, SolutionCallback jarg2_);
  public final static native void SolveWrapper_addLogCallback(long jarg1, SolveWrapper jarg1_, java.util.function.Consumer<String> jarg2);
  public final static native void SolveWrapper_addBestBoundCallback(long jarg1, SolveWrapper jarg1_, java.util.function.Consumer<Double> jarg2);
  public final static native byte[] SolveWrapper_solve(long jarg1, SolveWrapper jarg1_, byte[] jarg2);
  public final static native void SolveWrapper_stopSearch(long jarg1, SolveWrapper jarg1_);
  public final static native long new_SolveWrapper();
  public final static native void delete_SolveWrapper(long jarg1);
  public final static native String CpSatHelper_modelStats(byte[] jarg1);
  public final static native String CpSatHelper_solverResponseStats(byte[] jarg1);
  public final static native String CpSatHelper_validateModel(byte[] jarg1);
  public final static native long CpSatHelper_variableDomain(byte[] jarg1);
  public final static native boolean CpSatHelper_writeModelToFile(byte[] jarg1, String jarg2);
  public final static native long new_CpSatHelper();
  public final static native void delete_CpSatHelper(long jarg1);

  public static void SwigDirector_SolutionCallback_onSolutionCallback(SolutionCallback jself) {
    jself.onSolutionCallback();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
