/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.sat;

public class SolveWrapper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public SolveWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SolveWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(SolveWrapper obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_SolveWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParameters(com.google.ortools.sat.SatParameters parameters) {
    mainJNI.SolveWrapper_setParameters(swigCPtr, this, parameters.toByteArray());
  }

  public void addSolutionCallback(SolutionCallback callback) {
    mainJNI.SolveWrapper_addSolutionCallback(swigCPtr, this, SolutionCallback.getCPtr(callback), callback);
  }

  public void clearSolutionCallback(SolutionCallback callback) {
    mainJNI.SolveWrapper_clearSolutionCallback(swigCPtr, this, SolutionCallback.getCPtr(callback), callback);
  }

  public void addLogCallback(java.util.function.Consumer<String> log_callback) {
    mainJNI.SolveWrapper_addLogCallback(swigCPtr, this, log_callback);
  }

  public void addBestBoundCallback(java.util.function.Consumer<Double> best_bound_callback) {
    mainJNI.SolveWrapper_addBestBoundCallback(swigCPtr, this, best_bound_callback);
  }

  public com.google.ortools.sat.CpSolverResponse solve(com.google.ortools.sat.CpModelProto model_proto) {
  byte[] buf = mainJNI.SolveWrapper_solve(swigCPtr, this, model_proto.toByteArray());
  if (buf == null || buf.length == 0) {
    return null;
  }
  try {
    return com.google.ortools.sat.CpSolverResponse.parseFrom(buf);
  } catch (com.google.protobuf.InvalidProtocolBufferException e) {
    throw new RuntimeException(
        "Unable to parse com.google.ortools.sat.CpSolverResponse protocol message.");
  }
}

  public void stopSearch() {
    mainJNI.SolveWrapper_stopSearch(swigCPtr, this);
  }

  public SolveWrapper() {
    this(mainJNI.new_SolveWrapper(), true);
  }

}
