// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/sat/cp_model.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.sat;

/**
 * <pre>
 * A permutation of integers encoded as a list of cycles, hence the "sparse"
 * format. The image of an element cycle[i] is cycle[(i + 1) % cycle_length].
 * </pre>
 *
 * Protobuf type {@code operations_research.sat.SparsePermutationProto}
 */
public final class SparsePermutationProto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:operations_research.sat.SparsePermutationProto)
    SparsePermutationProtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      SparsePermutationProto.class.getName());
  }
  // Use SparsePermutationProto.newBuilder() to construct.
  private SparsePermutationProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SparsePermutationProto() {
    support_ = emptyIntList();
    cycleSizes_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ortools.sat.CpModelProtobuf.internal_static_operations_research_sat_SparsePermutationProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ortools.sat.CpModelProtobuf.internal_static_operations_research_sat_SparsePermutationProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ortools.sat.SparsePermutationProto.class, com.google.ortools.sat.SparsePermutationProto.Builder.class);
  }

  public static final int SUPPORT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList support_ =
      emptyIntList();
  /**
   * <pre>
   * Each cycle is listed one after the other in the support field.
   * The size of each cycle is given (in order) in the cycle_sizes field.
   * </pre>
   *
   * <code>repeated int32 support = 1;</code>
   * @return A list containing the support.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getSupportList() {
    return support_;
  }
  /**
   * <pre>
   * Each cycle is listed one after the other in the support field.
   * The size of each cycle is given (in order) in the cycle_sizes field.
   * </pre>
   *
   * <code>repeated int32 support = 1;</code>
   * @return The count of support.
   */
  public int getSupportCount() {
    return support_.size();
  }
  /**
   * <pre>
   * Each cycle is listed one after the other in the support field.
   * The size of each cycle is given (in order) in the cycle_sizes field.
   * </pre>
   *
   * <code>repeated int32 support = 1;</code>
   * @param index The index of the element to return.
   * @return The support at the given index.
   */
  public int getSupport(int index) {
    return support_.getInt(index);
  }
  private int supportMemoizedSerializedSize = -1;

  public static final int CYCLE_SIZES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList cycleSizes_ =
      emptyIntList();
  /**
   * <code>repeated int32 cycle_sizes = 2;</code>
   * @return A list containing the cycleSizes.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getCycleSizesList() {
    return cycleSizes_;
  }
  /**
   * <code>repeated int32 cycle_sizes = 2;</code>
   * @return The count of cycleSizes.
   */
  public int getCycleSizesCount() {
    return cycleSizes_.size();
  }
  /**
   * <code>repeated int32 cycle_sizes = 2;</code>
   * @param index The index of the element to return.
   * @return The cycleSizes at the given index.
   */
  public int getCycleSizes(int index) {
    return cycleSizes_.getInt(index);
  }
  private int cycleSizesMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getSupportList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(supportMemoizedSerializedSize);
    }
    for (int i = 0; i < support_.size(); i++) {
      output.writeInt32NoTag(support_.getInt(i));
    }
    if (getCycleSizesList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(cycleSizesMemoizedSerializedSize);
    }
    for (int i = 0; i < cycleSizes_.size(); i++) {
      output.writeInt32NoTag(cycleSizes_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < support_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(support_.getInt(i));
      }
      size += dataSize;
      if (!getSupportList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      supportMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cycleSizes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(cycleSizes_.getInt(i));
      }
      size += dataSize;
      if (!getCycleSizesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      cycleSizesMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ortools.sat.SparsePermutationProto)) {
      return super.equals(obj);
    }
    com.google.ortools.sat.SparsePermutationProto other = (com.google.ortools.sat.SparsePermutationProto) obj;

    if (!getSupportList()
        .equals(other.getSupportList())) return false;
    if (!getCycleSizesList()
        .equals(other.getCycleSizesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSupportCount() > 0) {
      hash = (37 * hash) + SUPPORT_FIELD_NUMBER;
      hash = (53 * hash) + getSupportList().hashCode();
    }
    if (getCycleSizesCount() > 0) {
      hash = (37 * hash) + CYCLE_SIZES_FIELD_NUMBER;
      hash = (53 * hash) + getCycleSizesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ortools.sat.SparsePermutationProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.ortools.sat.SparsePermutationProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.ortools.sat.SparsePermutationProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ortools.sat.SparsePermutationProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ortools.sat.SparsePermutationProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A permutation of integers encoded as a list of cycles, hence the "sparse"
   * format. The image of an element cycle[i] is cycle[(i + 1) % cycle_length].
   * </pre>
   *
   * Protobuf type {@code operations_research.sat.SparsePermutationProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:operations_research.sat.SparsePermutationProto)
      com.google.ortools.sat.SparsePermutationProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ortools.sat.CpModelProtobuf.internal_static_operations_research_sat_SparsePermutationProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ortools.sat.CpModelProtobuf.internal_static_operations_research_sat_SparsePermutationProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ortools.sat.SparsePermutationProto.class, com.google.ortools.sat.SparsePermutationProto.Builder.class);
    }

    // Construct using com.google.ortools.sat.SparsePermutationProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      support_ = emptyIntList();
      cycleSizes_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ortools.sat.CpModelProtobuf.internal_static_operations_research_sat_SparsePermutationProto_descriptor;
    }

    @java.lang.Override
    public com.google.ortools.sat.SparsePermutationProto getDefaultInstanceForType() {
      return com.google.ortools.sat.SparsePermutationProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ortools.sat.SparsePermutationProto build() {
      com.google.ortools.sat.SparsePermutationProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ortools.sat.SparsePermutationProto buildPartial() {
      com.google.ortools.sat.SparsePermutationProto result = new com.google.ortools.sat.SparsePermutationProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.ortools.sat.SparsePermutationProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        support_.makeImmutable();
        result.support_ = support_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        cycleSizes_.makeImmutable();
        result.cycleSizes_ = cycleSizes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ortools.sat.SparsePermutationProto) {
        return mergeFrom((com.google.ortools.sat.SparsePermutationProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ortools.sat.SparsePermutationProto other) {
      if (other == com.google.ortools.sat.SparsePermutationProto.getDefaultInstance()) return this;
      if (!other.support_.isEmpty()) {
        if (support_.isEmpty()) {
          support_ = other.support_;
          support_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureSupportIsMutable();
          support_.addAll(other.support_);
        }
        onChanged();
      }
      if (!other.cycleSizes_.isEmpty()) {
        if (cycleSizes_.isEmpty()) {
          cycleSizes_ = other.cycleSizes_;
          cycleSizes_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureCycleSizesIsMutable();
          cycleSizes_.addAll(other.cycleSizes_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int v = input.readInt32();
              ensureSupportIsMutable();
              support_.addInt(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureSupportIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                support_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 16: {
              int v = input.readInt32();
              ensureCycleSizesIsMutable();
              cycleSizes_.addInt(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureCycleSizesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                cycleSizes_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList support_ = emptyIntList();
    private void ensureSupportIsMutable() {
      if (!support_.isModifiable()) {
        support_ = makeMutableCopy(support_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Each cycle is listed one after the other in the support field.
     * The size of each cycle is given (in order) in the cycle_sizes field.
     * </pre>
     *
     * <code>repeated int32 support = 1;</code>
     * @return A list containing the support.
     */
    public java.util.List<java.lang.Integer>
        getSupportList() {
      support_.makeImmutable();
      return support_;
    }
    /**
     * <pre>
     * Each cycle is listed one after the other in the support field.
     * The size of each cycle is given (in order) in the cycle_sizes field.
     * </pre>
     *
     * <code>repeated int32 support = 1;</code>
     * @return The count of support.
     */
    public int getSupportCount() {
      return support_.size();
    }
    /**
     * <pre>
     * Each cycle is listed one after the other in the support field.
     * The size of each cycle is given (in order) in the cycle_sizes field.
     * </pre>
     *
     * <code>repeated int32 support = 1;</code>
     * @param index The index of the element to return.
     * @return The support at the given index.
     */
    public int getSupport(int index) {
      return support_.getInt(index);
    }
    /**
     * <pre>
     * Each cycle is listed one after the other in the support field.
     * The size of each cycle is given (in order) in the cycle_sizes field.
     * </pre>
     *
     * <code>repeated int32 support = 1;</code>
     * @param index The index to set the value at.
     * @param value The support to set.
     * @return This builder for chaining.
     */
    public Builder setSupport(
        int index, int value) {

      ensureSupportIsMutable();
      support_.setInt(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Each cycle is listed one after the other in the support field.
     * The size of each cycle is given (in order) in the cycle_sizes field.
     * </pre>
     *
     * <code>repeated int32 support = 1;</code>
     * @param value The support to add.
     * @return This builder for chaining.
     */
    public Builder addSupport(int value) {

      ensureSupportIsMutable();
      support_.addInt(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Each cycle is listed one after the other in the support field.
     * The size of each cycle is given (in order) in the cycle_sizes field.
     * </pre>
     *
     * <code>repeated int32 support = 1;</code>
     * @param values The support to add.
     * @return This builder for chaining.
     */
    public Builder addAllSupport(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureSupportIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, support_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Each cycle is listed one after the other in the support field.
     * The size of each cycle is given (in order) in the cycle_sizes field.
     * </pre>
     *
     * <code>repeated int32 support = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSupport() {
      support_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList cycleSizes_ = emptyIntList();
    private void ensureCycleSizesIsMutable() {
      if (!cycleSizes_.isModifiable()) {
        cycleSizes_ = makeMutableCopy(cycleSizes_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated int32 cycle_sizes = 2;</code>
     * @return A list containing the cycleSizes.
     */
    public java.util.List<java.lang.Integer>
        getCycleSizesList() {
      cycleSizes_.makeImmutable();
      return cycleSizes_;
    }
    /**
     * <code>repeated int32 cycle_sizes = 2;</code>
     * @return The count of cycleSizes.
     */
    public int getCycleSizesCount() {
      return cycleSizes_.size();
    }
    /**
     * <code>repeated int32 cycle_sizes = 2;</code>
     * @param index The index of the element to return.
     * @return The cycleSizes at the given index.
     */
    public int getCycleSizes(int index) {
      return cycleSizes_.getInt(index);
    }
    /**
     * <code>repeated int32 cycle_sizes = 2;</code>
     * @param index The index to set the value at.
     * @param value The cycleSizes to set.
     * @return This builder for chaining.
     */
    public Builder setCycleSizes(
        int index, int value) {

      ensureCycleSizesIsMutable();
      cycleSizes_.setInt(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 cycle_sizes = 2;</code>
     * @param value The cycleSizes to add.
     * @return This builder for chaining.
     */
    public Builder addCycleSizes(int value) {

      ensureCycleSizesIsMutable();
      cycleSizes_.addInt(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 cycle_sizes = 2;</code>
     * @param values The cycleSizes to add.
     * @return This builder for chaining.
     */
    public Builder addAllCycleSizes(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureCycleSizesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cycleSizes_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 cycle_sizes = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCycleSizes() {
      cycleSizes_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:operations_research.sat.SparsePermutationProto)
  }

  // @@protoc_insertion_point(class_scope:operations_research.sat.SparsePermutationProto)
  private static final com.google.ortools.sat.SparsePermutationProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ortools.sat.SparsePermutationProto();
  }

  public static com.google.ortools.sat.SparsePermutationProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SparsePermutationProto>
      PARSER = new com.google.protobuf.AbstractParser<SparsePermutationProto>() {
    @java.lang.Override
    public SparsePermutationProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SparsePermutationProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SparsePermutationProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ortools.sat.SparsePermutationProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

