// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/glop/parameters.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.glop;

public interface GlopParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.glop.GlopParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .operations_research.glop.GlopParameters.ScalingAlgorithm scaling_method = 57 [default = EQUILIBRATION];</code>
   * @return Whether the scalingMethod field is set.
   */
  boolean hasScalingMethod();
  /**
   * <code>optional .operations_research.glop.GlopParameters.ScalingAlgorithm scaling_method = 57 [default = EQUILIBRATION];</code>
   * @return The scalingMethod.
   */
  com.google.ortools.glop.GlopParameters.ScalingAlgorithm getScalingMethod();

  /**
   * <pre>
   * PricingRule to use during the feasibility phase.
   * </pre>
   *
   * <code>optional .operations_research.glop.GlopParameters.PricingRule feasibility_rule = 1 [default = STEEPEST_EDGE];</code>
   * @return Whether the feasibilityRule field is set.
   */
  boolean hasFeasibilityRule();
  /**
   * <pre>
   * PricingRule to use during the feasibility phase.
   * </pre>
   *
   * <code>optional .operations_research.glop.GlopParameters.PricingRule feasibility_rule = 1 [default = STEEPEST_EDGE];</code>
   * @return The feasibilityRule.
   */
  com.google.ortools.glop.GlopParameters.PricingRule getFeasibilityRule();

  /**
   * <pre>
   * PricingRule to use during the optimization phase.
   * </pre>
   *
   * <code>optional .operations_research.glop.GlopParameters.PricingRule optimization_rule = 2 [default = STEEPEST_EDGE];</code>
   * @return Whether the optimizationRule field is set.
   */
  boolean hasOptimizationRule();
  /**
   * <pre>
   * PricingRule to use during the optimization phase.
   * </pre>
   *
   * <code>optional .operations_research.glop.GlopParameters.PricingRule optimization_rule = 2 [default = STEEPEST_EDGE];</code>
   * @return The optimizationRule.
   */
  com.google.ortools.glop.GlopParameters.PricingRule getOptimizationRule();

  /**
   * <pre>
   * We estimate the factorization accuracy of B during each pivot by using
   * the fact that we can compute the pivot coefficient in two ways:
   * - From direction[leaving_row].
   * - From update_row[entering_column].
   * If the two values have a relative difference above this threshold, we
   * trigger a refactorization.
   * </pre>
   *
   * <code>optional double refactorization_threshold = 6 [default = 1e-09];</code>
   * @return Whether the refactorizationThreshold field is set.
   */
  boolean hasRefactorizationThreshold();
  /**
   * <pre>
   * We estimate the factorization accuracy of B during each pivot by using
   * the fact that we can compute the pivot coefficient in two ways:
   * - From direction[leaving_row].
   * - From update_row[entering_column].
   * If the two values have a relative difference above this threshold, we
   * trigger a refactorization.
   * </pre>
   *
   * <code>optional double refactorization_threshold = 6 [default = 1e-09];</code>
   * @return The refactorizationThreshold.
   */
  double getRefactorizationThreshold();

  /**
   * <pre>
   * We estimate the accuracy of the iteratively computed reduced costs. If
   * it falls below this threshold, we reinitialize them from scratch. Note
   * that such an operation is pretty fast, so we can use a low threshold.
   * It is important to have a good accuracy here (better than the
   * dual_feasibility_tolerance below) to be sure of the sign of such a cost.
   * </pre>
   *
   * <code>optional double recompute_reduced_costs_threshold = 8 [default = 1e-08];</code>
   * @return Whether the recomputeReducedCostsThreshold field is set.
   */
  boolean hasRecomputeReducedCostsThreshold();
  /**
   * <pre>
   * We estimate the accuracy of the iteratively computed reduced costs. If
   * it falls below this threshold, we reinitialize them from scratch. Note
   * that such an operation is pretty fast, so we can use a low threshold.
   * It is important to have a good accuracy here (better than the
   * dual_feasibility_tolerance below) to be sure of the sign of such a cost.
   * </pre>
   *
   * <code>optional double recompute_reduced_costs_threshold = 8 [default = 1e-08];</code>
   * @return The recomputeReducedCostsThreshold.
   */
  double getRecomputeReducedCostsThreshold();

  /**
   * <pre>
   * Note that the threshold is a relative error on the actual norm (not the
   * squared one) and that edge norms are always greater than 1. Recomputing
   * norms is a really expensive operation and a large threshold is ok since
   * this doesn't impact directly the solution but just the entering variable
   * choice.
   * </pre>
   *
   * <code>optional double recompute_edges_norm_threshold = 9 [default = 100];</code>
   * @return Whether the recomputeEdgesNormThreshold field is set.
   */
  boolean hasRecomputeEdgesNormThreshold();
  /**
   * <pre>
   * Note that the threshold is a relative error on the actual norm (not the
   * squared one) and that edge norms are always greater than 1. Recomputing
   * norms is a really expensive operation and a large threshold is ok since
   * this doesn't impact directly the solution but just the entering variable
   * choice.
   * </pre>
   *
   * <code>optional double recompute_edges_norm_threshold = 9 [default = 100];</code>
   * @return The recomputeEdgesNormThreshold.
   */
  double getRecomputeEdgesNormThreshold();

  /**
   * <pre>
   * This tolerance indicates by how much we allow the variable values to go out
   * of bounds and still consider the current solution primal-feasible. We also
   * use the same tolerance for the error A.x - b. Note that the two errors are
   * closely related if A is scaled in such a way that the greatest coefficient
   * magnitude on each column is 1.0.
   *
   * This is also simply called feasibility tolerance in other solvers.
   * </pre>
   *
   * <code>optional double primal_feasibility_tolerance = 10 [default = 1e-08];</code>
   * @return Whether the primalFeasibilityTolerance field is set.
   */
  boolean hasPrimalFeasibilityTolerance();
  /**
   * <pre>
   * This tolerance indicates by how much we allow the variable values to go out
   * of bounds and still consider the current solution primal-feasible. We also
   * use the same tolerance for the error A.x - b. Note that the two errors are
   * closely related if A is scaled in such a way that the greatest coefficient
   * magnitude on each column is 1.0.
   *
   * This is also simply called feasibility tolerance in other solvers.
   * </pre>
   *
   * <code>optional double primal_feasibility_tolerance = 10 [default = 1e-08];</code>
   * @return The primalFeasibilityTolerance.
   */
  double getPrimalFeasibilityTolerance();

  /**
   * <pre>
   * Variables whose reduced costs have an absolute value smaller than this
   * tolerance are not considered as entering candidates. That is they do not
   * take part in deciding whether a solution is dual-feasible or not.
   *
   * Note that this value can temporarily increase during the execution of the
   * algorithm if the estimated precision of the reduced costs is higher than
   * this tolerance. Note also that we scale the costs (in the presolve step) so
   * that the cost magnitude range contains one.
   *
   * This is also known as the optimality tolerance in other solvers.
   * </pre>
   *
   * <code>optional double dual_feasibility_tolerance = 11 [default = 1e-08];</code>
   * @return Whether the dualFeasibilityTolerance field is set.
   */
  boolean hasDualFeasibilityTolerance();
  /**
   * <pre>
   * Variables whose reduced costs have an absolute value smaller than this
   * tolerance are not considered as entering candidates. That is they do not
   * take part in deciding whether a solution is dual-feasible or not.
   *
   * Note that this value can temporarily increase during the execution of the
   * algorithm if the estimated precision of the reduced costs is higher than
   * this tolerance. Note also that we scale the costs (in the presolve step) so
   * that the cost magnitude range contains one.
   *
   * This is also known as the optimality tolerance in other solvers.
   * </pre>
   *
   * <code>optional double dual_feasibility_tolerance = 11 [default = 1e-08];</code>
   * @return The dualFeasibilityTolerance.
   */
  double getDualFeasibilityTolerance();

  /**
   * <pre>
   * During the primal simplex (resp. dual simplex), the coefficients of the
   * direction (resp. update row) with a magnitude lower than this threshold are
   * not considered during the ratio test. This tolerance is related to the
   * precision at which a Solve() involving the basis matrix can be performed.
   *
   * TODO(user): Automatically increase it when we detect that the precision
   * of the Solve() is worse than this.
   * </pre>
   *
   * <code>optional double ratio_test_zero_threshold = 12 [default = 1e-09];</code>
   * @return Whether the ratioTestZeroThreshold field is set.
   */
  boolean hasRatioTestZeroThreshold();
  /**
   * <pre>
   * During the primal simplex (resp. dual simplex), the coefficients of the
   * direction (resp. update row) with a magnitude lower than this threshold are
   * not considered during the ratio test. This tolerance is related to the
   * precision at which a Solve() involving the basis matrix can be performed.
   *
   * TODO(user): Automatically increase it when we detect that the precision
   * of the Solve() is worse than this.
   * </pre>
   *
   * <code>optional double ratio_test_zero_threshold = 12 [default = 1e-09];</code>
   * @return The ratioTestZeroThreshold.
   */
  double getRatioTestZeroThreshold();

  /**
   * <pre>
   * This impacts the ratio test and indicates by how much we allow a basic
   * variable value that we move to go out of bounds. The value should be in
   * [0.0, 1.0) and should be interpreted as a ratio of the
   * primal_feasibility_tolerance. Setting this to 0.0 basically disables the
   * Harris ratio test while setting this too close to 1.0 will make it
   * difficult to keep the variable values inside their bounds modulo the
   * primal_feasibility_tolerance.
   *
   * Note that the same comment applies to the dual simplex ratio test. There,
   * we allow the reduced costs to be of an infeasible sign by as much as this
   * ratio times the dual_feasibility_tolerance.
   * </pre>
   *
   * <code>optional double harris_tolerance_ratio = 13 [default = 0.5];</code>
   * @return Whether the harrisToleranceRatio field is set.
   */
  boolean hasHarrisToleranceRatio();
  /**
   * <pre>
   * This impacts the ratio test and indicates by how much we allow a basic
   * variable value that we move to go out of bounds. The value should be in
   * [0.0, 1.0) and should be interpreted as a ratio of the
   * primal_feasibility_tolerance. Setting this to 0.0 basically disables the
   * Harris ratio test while setting this too close to 1.0 will make it
   * difficult to keep the variable values inside their bounds modulo the
   * primal_feasibility_tolerance.
   *
   * Note that the same comment applies to the dual simplex ratio test. There,
   * we allow the reduced costs to be of an infeasible sign by as much as this
   * ratio times the dual_feasibility_tolerance.
   * </pre>
   *
   * <code>optional double harris_tolerance_ratio = 13 [default = 0.5];</code>
   * @return The harrisToleranceRatio.
   */
  double getHarrisToleranceRatio();

  /**
   * <pre>
   * When we choose the leaving variable, we want to avoid small pivot because
   * they are the less precise and may cause numerical instabilities. For a
   * pivot under this threshold times the infinity norm of the direction, we try
   * various countermeasures in order to avoid using it.
   * </pre>
   *
   * <code>optional double small_pivot_threshold = 14 [default = 1e-06];</code>
   * @return Whether the smallPivotThreshold field is set.
   */
  boolean hasSmallPivotThreshold();
  /**
   * <pre>
   * When we choose the leaving variable, we want to avoid small pivot because
   * they are the less precise and may cause numerical instabilities. For a
   * pivot under this threshold times the infinity norm of the direction, we try
   * various countermeasures in order to avoid using it.
   * </pre>
   *
   * <code>optional double small_pivot_threshold = 14 [default = 1e-06];</code>
   * @return The smallPivotThreshold.
   */
  double getSmallPivotThreshold();

  /**
   * <pre>
   * We never follow a basis change with a pivot under this threshold.
   * </pre>
   *
   * <code>optional double minimum_acceptable_pivot = 15 [default = 1e-06];</code>
   * @return Whether the minimumAcceptablePivot field is set.
   */
  boolean hasMinimumAcceptablePivot();
  /**
   * <pre>
   * We never follow a basis change with a pivot under this threshold.
   * </pre>
   *
   * <code>optional double minimum_acceptable_pivot = 15 [default = 1e-06];</code>
   * @return The minimumAcceptablePivot.
   */
  double getMinimumAcceptablePivot();

  /**
   * <pre>
   * In order to increase the sparsity of the manipulated vectors, floating
   * point values with a magnitude smaller than this parameter are set to zero
   * (only in some places). This parameter should be positive or zero.
   * </pre>
   *
   * <code>optional double drop_tolerance = 52 [default = 1e-14];</code>
   * @return Whether the dropTolerance field is set.
   */
  boolean hasDropTolerance();
  /**
   * <pre>
   * In order to increase the sparsity of the manipulated vectors, floating
   * point values with a magnitude smaller than this parameter are set to zero
   * (only in some places). This parameter should be positive or zero.
   * </pre>
   *
   * <code>optional double drop_tolerance = 52 [default = 1e-14];</code>
   * @return The dropTolerance.
   */
  double getDropTolerance();

  /**
   * <pre>
   * Whether or not we scale the matrix A so that the maximum coefficient on
   * each line and each column is 1.0.
   * </pre>
   *
   * <code>optional bool use_scaling = 16 [default = true];</code>
   * @return Whether the useScaling field is set.
   */
  boolean hasUseScaling();
  /**
   * <pre>
   * Whether or not we scale the matrix A so that the maximum coefficient on
   * each line and each column is 1.0.
   * </pre>
   *
   * <code>optional bool use_scaling = 16 [default = true];</code>
   * @return The useScaling.
   */
  boolean getUseScaling();

  /**
   * <code>optional .operations_research.glop.GlopParameters.CostScalingAlgorithm cost_scaling = 60 [default = CONTAIN_ONE_COST_SCALING];</code>
   * @return Whether the costScaling field is set.
   */
  boolean hasCostScaling();
  /**
   * <code>optional .operations_research.glop.GlopParameters.CostScalingAlgorithm cost_scaling = 60 [default = CONTAIN_ONE_COST_SCALING];</code>
   * @return The costScaling.
   */
  com.google.ortools.glop.GlopParameters.CostScalingAlgorithm getCostScaling();

  /**
   * <pre>
   * What heuristic is used to try to replace the fixed slack columns in the
   * initial basis of the primal simplex.
   * </pre>
   *
   * <code>optional .operations_research.glop.GlopParameters.InitialBasisHeuristic initial_basis = 17 [default = TRIANGULAR];</code>
   * @return Whether the initialBasis field is set.
   */
  boolean hasInitialBasis();
  /**
   * <pre>
   * What heuristic is used to try to replace the fixed slack columns in the
   * initial basis of the primal simplex.
   * </pre>
   *
   * <code>optional .operations_research.glop.GlopParameters.InitialBasisHeuristic initial_basis = 17 [default = TRIANGULAR];</code>
   * @return The initialBasis.
   */
  com.google.ortools.glop.GlopParameters.InitialBasisHeuristic getInitialBasis();

  /**
   * <pre>
   * Whether or not we keep a transposed version of the matrix A to speed-up the
   * pricing at the cost of extra memory and the initial tranposition
   * computation.
   * </pre>
   *
   * <code>optional bool use_transposed_matrix = 18 [default = true];</code>
   * @return Whether the useTransposedMatrix field is set.
   */
  boolean hasUseTransposedMatrix();
  /**
   * <pre>
   * Whether or not we keep a transposed version of the matrix A to speed-up the
   * pricing at the cost of extra memory and the initial tranposition
   * computation.
   * </pre>
   *
   * <code>optional bool use_transposed_matrix = 18 [default = true];</code>
   * @return The useTransposedMatrix.
   */
  boolean getUseTransposedMatrix();

  /**
   * <pre>
   * Number of iterations between two basis refactorizations. Note that various
   * conditions in the algorithm may trigger a refactorization before this
   * period is reached. Set this to 0 if you want to refactorize at each step.
   * </pre>
   *
   * <code>optional int32 basis_refactorization_period = 19 [default = 64];</code>
   * @return Whether the basisRefactorizationPeriod field is set.
   */
  boolean hasBasisRefactorizationPeriod();
  /**
   * <pre>
   * Number of iterations between two basis refactorizations. Note that various
   * conditions in the algorithm may trigger a refactorization before this
   * period is reached. Set this to 0 if you want to refactorize at each step.
   * </pre>
   *
   * <code>optional int32 basis_refactorization_period = 19 [default = 64];</code>
   * @return The basisRefactorizationPeriod.
   */
  int getBasisRefactorizationPeriod();

  /**
   * <pre>
   * If this is true, then basis_refactorization_period becomes a lower bound on
   * the number of iterations between two refactorization (provided there is no
   * numerical accuracy issues). Depending on the estimated time to refactorize
   * vs the extra time spend in each solves because of the LU update, we try to
   * balance the two times.
   * </pre>
   *
   * <code>optional bool dynamically_adjust_refactorization_period = 63 [default = true];</code>
   * @return Whether the dynamicallyAdjustRefactorizationPeriod field is set.
   */
  boolean hasDynamicallyAdjustRefactorizationPeriod();
  /**
   * <pre>
   * If this is true, then basis_refactorization_period becomes a lower bound on
   * the number of iterations between two refactorization (provided there is no
   * numerical accuracy issues). Depending on the estimated time to refactorize
   * vs the extra time spend in each solves because of the LU update, we try to
   * balance the two times.
   * </pre>
   *
   * <code>optional bool dynamically_adjust_refactorization_period = 63 [default = true];</code>
   * @return The dynamicallyAdjustRefactorizationPeriod.
   */
  boolean getDynamicallyAdjustRefactorizationPeriod();

  /**
   * <pre>
   * Whether or not we solve the dual of the given problem.
   * With a value of auto, the algorithm decide which approach is probably the
   * fastest depending on the problem dimensions (see dualizer_threshold).
   * </pre>
   *
   * <code>optional .operations_research.glop.GlopParameters.SolverBehavior solve_dual_problem = 20 [default = LET_SOLVER_DECIDE];</code>
   * @return Whether the solveDualProblem field is set.
   */
  boolean hasSolveDualProblem();
  /**
   * <pre>
   * Whether or not we solve the dual of the given problem.
   * With a value of auto, the algorithm decide which approach is probably the
   * fastest depending on the problem dimensions (see dualizer_threshold).
   * </pre>
   *
   * <code>optional .operations_research.glop.GlopParameters.SolverBehavior solve_dual_problem = 20 [default = LET_SOLVER_DECIDE];</code>
   * @return The solveDualProblem.
   */
  com.google.ortools.glop.GlopParameters.SolverBehavior getSolveDualProblem();

  /**
   * <pre>
   * When solve_dual_problem is LET_SOLVER_DECIDE, take the dual if the number
   * of constraints of the problem is more than this threshold times the number
   * of variables.
   * </pre>
   *
   * <code>optional double dualizer_threshold = 21 [default = 1.5];</code>
   * @return Whether the dualizerThreshold field is set.
   */
  boolean hasDualizerThreshold();
  /**
   * <pre>
   * When solve_dual_problem is LET_SOLVER_DECIDE, take the dual if the number
   * of constraints of the problem is more than this threshold times the number
   * of variables.
   * </pre>
   *
   * <code>optional double dualizer_threshold = 21 [default = 1.5];</code>
   * @return The dualizerThreshold.
   */
  double getDualizerThreshold();

  /**
   * <pre>
   * When the problem status is OPTIMAL, we check the optimality using this
   * relative tolerance and change the status to IMPRECISE if an issue is
   * detected.
   *
   * The tolerance is "relative" in the sense that our thresholds are:
   * - tolerance * max(1.0, abs(bound)) for crossing a given bound.
   * - tolerance * max(1.0, abs(cost)) for an infeasible reduced cost.
   * - tolerance for an infeasible dual value.
   * </pre>
   *
   * <code>optional double solution_feasibility_tolerance = 22 [default = 1e-06];</code>
   * @return Whether the solutionFeasibilityTolerance field is set.
   */
  boolean hasSolutionFeasibilityTolerance();
  /**
   * <pre>
   * When the problem status is OPTIMAL, we check the optimality using this
   * relative tolerance and change the status to IMPRECISE if an issue is
   * detected.
   *
   * The tolerance is "relative" in the sense that our thresholds are:
   * - tolerance * max(1.0, abs(bound)) for crossing a given bound.
   * - tolerance * max(1.0, abs(cost)) for an infeasible reduced cost.
   * - tolerance for an infeasible dual value.
   * </pre>
   *
   * <code>optional double solution_feasibility_tolerance = 22 [default = 1e-06];</code>
   * @return The solutionFeasibilityTolerance.
   */
  double getSolutionFeasibilityTolerance();

  /**
   * <pre>
   * If true, then when the solver returns a solution with an OPTIMAL status,
   * we can guarantee that:
   * - The primal variable are in their bounds.
   * - The dual variable are in their bounds.
   * - If we modify each component of the right-hand side a bit and each
   * component of the objective function a bit, then the pair (primal values,
   * dual values) is an EXACT optimal solution of the perturbed problem.
   * - The modifications above are smaller than the associated tolerances as
   * defined in the comment for solution_feasibility_tolerance (*).
   *
   * (*): This is the only place where the guarantee is not tight since we
   * compute the upper bounds with scalar product of the primal/dual
   * solution and the initial problem coefficients with only double precision.
   *
   * Note that whether or not this option is true, we still check the
   * primal/dual infeasibility and objective gap. However if it is false, we
   * don't move the primal/dual values within their bounds and leave them
   * untouched.
   * </pre>
   *
   * <code>optional bool provide_strong_optimal_guarantee = 24 [default = true];</code>
   * @return Whether the provideStrongOptimalGuarantee field is set.
   */
  boolean hasProvideStrongOptimalGuarantee();
  /**
   * <pre>
   * If true, then when the solver returns a solution with an OPTIMAL status,
   * we can guarantee that:
   * - The primal variable are in their bounds.
   * - The dual variable are in their bounds.
   * - If we modify each component of the right-hand side a bit and each
   * component of the objective function a bit, then the pair (primal values,
   * dual values) is an EXACT optimal solution of the perturbed problem.
   * - The modifications above are smaller than the associated tolerances as
   * defined in the comment for solution_feasibility_tolerance (*).
   *
   * (*): This is the only place where the guarantee is not tight since we
   * compute the upper bounds with scalar product of the primal/dual
   * solution and the initial problem coefficients with only double precision.
   *
   * Note that whether or not this option is true, we still check the
   * primal/dual infeasibility and objective gap. However if it is false, we
   * don't move the primal/dual values within their bounds and leave them
   * untouched.
   * </pre>
   *
   * <code>optional bool provide_strong_optimal_guarantee = 24 [default = true];</code>
   * @return The provideStrongOptimalGuarantee.
   */
  boolean getProvideStrongOptimalGuarantee();

  /**
   * <pre>
   * If true, the internal API will change the return status to imprecise if the
   * solution does not respect the internal tolerances.
   * </pre>
   *
   * <code>optional bool change_status_to_imprecise = 58 [default = true];</code>
   * @return Whether the changeStatusToImprecise field is set.
   */
  boolean hasChangeStatusToImprecise();
  /**
   * <pre>
   * If true, the internal API will change the return status to imprecise if the
   * solution does not respect the internal tolerances.
   * </pre>
   *
   * <code>optional bool change_status_to_imprecise = 58 [default = true];</code>
   * @return The changeStatusToImprecise.
   */
  boolean getChangeStatusToImprecise();

  /**
   * <pre>
   * When the solution of phase II is imprecise, we re-run the phase II with the
   * opposite algorithm from that imprecise solution (i.e., if primal or dual
   * simplex was used, we use dual or primal simplex, respectively). We repeat
   * such re-optimization until the solution is precise, or we hit this limit.
   * </pre>
   *
   * <code>optional double max_number_of_reoptimizations = 56 [default = 40];</code>
   * @return Whether the maxNumberOfReoptimizations field is set.
   */
  boolean hasMaxNumberOfReoptimizations();
  /**
   * <pre>
   * When the solution of phase II is imprecise, we re-run the phase II with the
   * opposite algorithm from that imprecise solution (i.e., if primal or dual
   * simplex was used, we use dual or primal simplex, respectively). We repeat
   * such re-optimization until the solution is precise, or we hit this limit.
   * </pre>
   *
   * <code>optional double max_number_of_reoptimizations = 56 [default = 40];</code>
   * @return The maxNumberOfReoptimizations.
   */
  double getMaxNumberOfReoptimizations();

  /**
   * <pre>
   * Threshold for LU-factorization: for stability reasons, the magnitude of the
   * chosen pivot at a given step is guaranteed to be greater than this
   * threshold times the maximum magnitude of all the possible pivot choices in
   * the same column. The value must be in [0,1].
   * </pre>
   *
   * <code>optional double lu_factorization_pivot_threshold = 25 [default = 0.01];</code>
   * @return Whether the luFactorizationPivotThreshold field is set.
   */
  boolean hasLuFactorizationPivotThreshold();
  /**
   * <pre>
   * Threshold for LU-factorization: for stability reasons, the magnitude of the
   * chosen pivot at a given step is guaranteed to be greater than this
   * threshold times the maximum magnitude of all the possible pivot choices in
   * the same column. The value must be in [0,1].
   * </pre>
   *
   * <code>optional double lu_factorization_pivot_threshold = 25 [default = 0.01];</code>
   * @return The luFactorizationPivotThreshold.
   */
  double getLuFactorizationPivotThreshold();

  /**
   * <pre>
   * Maximum time allowed in seconds to solve a problem.
   * </pre>
   *
   * <code>optional double max_time_in_seconds = 26 [default = inf];</code>
   * @return Whether the maxTimeInSeconds field is set.
   */
  boolean hasMaxTimeInSeconds();
  /**
   * <pre>
   * Maximum time allowed in seconds to solve a problem.
   * </pre>
   *
   * <code>optional double max_time_in_seconds = 26 [default = inf];</code>
   * @return The maxTimeInSeconds.
   */
  double getMaxTimeInSeconds();

  /**
   * <pre>
   * Maximum deterministic time allowed to solve a problem. The deterministic
   * time is more or less correlated to the running time, and its unit should
   * be around the second (at least on a Xeon(R) CPU E5-1650 v2 &#64; 3.50GHz).
   *
   * TODO(user): Improve the correlation.
   * </pre>
   *
   * <code>optional double max_deterministic_time = 45 [default = inf];</code>
   * @return Whether the maxDeterministicTime field is set.
   */
  boolean hasMaxDeterministicTime();
  /**
   * <pre>
   * Maximum deterministic time allowed to solve a problem. The deterministic
   * time is more or less correlated to the running time, and its unit should
   * be around the second (at least on a Xeon(R) CPU E5-1650 v2 &#64; 3.50GHz).
   *
   * TODO(user): Improve the correlation.
   * </pre>
   *
   * <code>optional double max_deterministic_time = 45 [default = inf];</code>
   * @return The maxDeterministicTime.
   */
  double getMaxDeterministicTime();

  /**
   * <pre>
   * Maximum number of simplex iterations to solve a problem.
   * A value of -1 means no limit.
   * </pre>
   *
   * <code>optional int64 max_number_of_iterations = 27 [default = -1];</code>
   * @return Whether the maxNumberOfIterations field is set.
   */
  boolean hasMaxNumberOfIterations();
  /**
   * <pre>
   * Maximum number of simplex iterations to solve a problem.
   * A value of -1 means no limit.
   * </pre>
   *
   * <code>optional int64 max_number_of_iterations = 27 [default = -1];</code>
   * @return The maxNumberOfIterations.
   */
  long getMaxNumberOfIterations();

  /**
   * <pre>
   * How many columns do we look at in the Markowitz pivoting rule to find
   * a good pivot. See markowitz.h.
   * </pre>
   *
   * <code>optional int32 markowitz_zlatev_parameter = 29 [default = 3];</code>
   * @return Whether the markowitzZlatevParameter field is set.
   */
  boolean hasMarkowitzZlatevParameter();
  /**
   * <pre>
   * How many columns do we look at in the Markowitz pivoting rule to find
   * a good pivot. See markowitz.h.
   * </pre>
   *
   * <code>optional int32 markowitz_zlatev_parameter = 29 [default = 3];</code>
   * @return The markowitzZlatevParameter.
   */
  int getMarkowitzZlatevParameter();

  /**
   * <pre>
   * If a pivot magnitude is smaller than this during the Markowitz LU
   * factorization, then the matrix is assumed to be singular. Note that
   * this is an absolute threshold and is not relative to the other possible
   * pivots on the same column (see lu_factorization_pivot_threshold).
   * </pre>
   *
   * <code>optional double markowitz_singularity_threshold = 30 [default = 1e-15];</code>
   * @return Whether the markowitzSingularityThreshold field is set.
   */
  boolean hasMarkowitzSingularityThreshold();
  /**
   * <pre>
   * If a pivot magnitude is smaller than this during the Markowitz LU
   * factorization, then the matrix is assumed to be singular. Note that
   * this is an absolute threshold and is not relative to the other possible
   * pivots on the same column (see lu_factorization_pivot_threshold).
   * </pre>
   *
   * <code>optional double markowitz_singularity_threshold = 30 [default = 1e-15];</code>
   * @return The markowitzSingularityThreshold.
   */
  double getMarkowitzSingularityThreshold();

  /**
   * <pre>
   * Whether or not we use the dual simplex algorithm instead of the primal.
   * </pre>
   *
   * <code>optional bool use_dual_simplex = 31 [default = false];</code>
   * @return Whether the useDualSimplex field is set.
   */
  boolean hasUseDualSimplex();
  /**
   * <pre>
   * Whether or not we use the dual simplex algorithm instead of the primal.
   * </pre>
   *
   * <code>optional bool use_dual_simplex = 31 [default = false];</code>
   * @return The useDualSimplex.
   */
  boolean getUseDualSimplex();

  /**
   * <pre>
   * During incremental solve, let the solver decide if it use the primal or
   * dual simplex algorithm depending on the current solution and on the new
   * problem. Note that even if this is true, the value of use_dual_simplex
   * still indicates the default algorithm that the solver will use.
   * </pre>
   *
   * <code>optional bool allow_simplex_algorithm_change = 32 [default = false];</code>
   * @return Whether the allowSimplexAlgorithmChange field is set.
   */
  boolean hasAllowSimplexAlgorithmChange();
  /**
   * <pre>
   * During incremental solve, let the solver decide if it use the primal or
   * dual simplex algorithm depending on the current solution and on the new
   * problem. Note that even if this is true, the value of use_dual_simplex
   * still indicates the default algorithm that the solver will use.
   * </pre>
   *
   * <code>optional bool allow_simplex_algorithm_change = 32 [default = false];</code>
   * @return The allowSimplexAlgorithmChange.
   */
  boolean getAllowSimplexAlgorithmChange();

  /**
   * <pre>
   * Devex weights will be reset to 1.0 after that number of updates.
   * </pre>
   *
   * <code>optional int32 devex_weights_reset_period = 33 [default = 150];</code>
   * @return Whether the devexWeightsResetPeriod field is set.
   */
  boolean hasDevexWeightsResetPeriod();
  /**
   * <pre>
   * Devex weights will be reset to 1.0 after that number of updates.
   * </pre>
   *
   * <code>optional int32 devex_weights_reset_period = 33 [default = 150];</code>
   * @return The devexWeightsResetPeriod.
   */
  int getDevexWeightsResetPeriod();

  /**
   * <pre>
   * Whether or not we use advanced preprocessing techniques.
   * </pre>
   *
   * <code>optional bool use_preprocessing = 34 [default = true];</code>
   * @return Whether the usePreprocessing field is set.
   */
  boolean hasUsePreprocessing();
  /**
   * <pre>
   * Whether or not we use advanced preprocessing techniques.
   * </pre>
   *
   * <code>optional bool use_preprocessing = 34 [default = true];</code>
   * @return The usePreprocessing.
   */
  boolean getUsePreprocessing();

  /**
   * <pre>
   * Whether or not to use the middle product form update rather than the
   * standard eta LU update. The middle form product update should be a lot more
   * efficient (close to the Forrest-Tomlin update, a bit slower but easier to
   * implement). See for more details:
   * Qi Huangfu, J. A. Julian Hall, "Novel update techniques for the revised
   * simplex method", 28 january 2013, Technical Report ERGO-13-0001
   * http://www.maths.ed.ac.uk/hall/HuHa12/ERGO-13-001.pdf
   * </pre>
   *
   * <code>optional bool use_middle_product_form_update = 35 [default = true];</code>
   * @return Whether the useMiddleProductFormUpdate field is set.
   */
  boolean hasUseMiddleProductFormUpdate();
  /**
   * <pre>
   * Whether or not to use the middle product form update rather than the
   * standard eta LU update. The middle form product update should be a lot more
   * efficient (close to the Forrest-Tomlin update, a bit slower but easier to
   * implement). See for more details:
   * Qi Huangfu, J. A. Julian Hall, "Novel update techniques for the revised
   * simplex method", 28 january 2013, Technical Report ERGO-13-0001
   * http://www.maths.ed.ac.uk/hall/HuHa12/ERGO-13-001.pdf
   * </pre>
   *
   * <code>optional bool use_middle_product_form_update = 35 [default = true];</code>
   * @return The useMiddleProductFormUpdate.
   */
  boolean getUseMiddleProductFormUpdate();

  /**
   * <pre>
   * Whether we initialize devex weights to 1.0 or to the norms of the matrix
   * columns.
   * </pre>
   *
   * <code>optional bool initialize_devex_with_column_norms = 36 [default = true];</code>
   * @return Whether the initializeDevexWithColumnNorms field is set.
   */
  boolean hasInitializeDevexWithColumnNorms();
  /**
   * <pre>
   * Whether we initialize devex weights to 1.0 or to the norms of the matrix
   * columns.
   * </pre>
   *
   * <code>optional bool initialize_devex_with_column_norms = 36 [default = true];</code>
   * @return The initializeDevexWithColumnNorms.
   */
  boolean getInitializeDevexWithColumnNorms();

  /**
   * <pre>
   * Whether or not we exploit the singleton columns already present in the
   * problem when we create the initial basis.
   * </pre>
   *
   * <code>optional bool exploit_singleton_column_in_initial_basis = 37 [default = true];</code>
   * @return Whether the exploitSingletonColumnInInitialBasis field is set.
   */
  boolean hasExploitSingletonColumnInInitialBasis();
  /**
   * <pre>
   * Whether or not we exploit the singleton columns already present in the
   * problem when we create the initial basis.
   * </pre>
   *
   * <code>optional bool exploit_singleton_column_in_initial_basis = 37 [default = true];</code>
   * @return The exploitSingletonColumnInInitialBasis.
   */
  boolean getExploitSingletonColumnInInitialBasis();

  /**
   * <pre>
   * Like small_pivot_threshold but for the dual simplex. This is needed because
   * the dual algorithm does not interpret this value in the same way.
   * TODO(user): Clean this up and use the same small pivot detection.
   * </pre>
   *
   * <code>optional double dual_small_pivot_threshold = 38 [default = 0.0001];</code>
   * @return Whether the dualSmallPivotThreshold field is set.
   */
  boolean hasDualSmallPivotThreshold();
  /**
   * <pre>
   * Like small_pivot_threshold but for the dual simplex. This is needed because
   * the dual algorithm does not interpret this value in the same way.
   * TODO(user): Clean this up and use the same small pivot detection.
   * </pre>
   *
   * <code>optional double dual_small_pivot_threshold = 38 [default = 0.0001];</code>
   * @return The dualSmallPivotThreshold.
   */
  double getDualSmallPivotThreshold();

  /**
   * <pre>
   * A floating point tolerance used by the preprocessors. This is used for
   * things like detecting if two columns/rows are proportional or if an
   * interval is empty.
   *
   * Note that the preprocessors also use solution_feasibility_tolerance() to
   * detect if a problem is infeasible.
   * </pre>
   *
   * <code>optional double preprocessor_zero_tolerance = 39 [default = 1e-09];</code>
   * @return Whether the preprocessorZeroTolerance field is set.
   */
  boolean hasPreprocessorZeroTolerance();
  /**
   * <pre>
   * A floating point tolerance used by the preprocessors. This is used for
   * things like detecting if two columns/rows are proportional or if an
   * interval is empty.
   *
   * Note that the preprocessors also use solution_feasibility_tolerance() to
   * detect if a problem is infeasible.
   * </pre>
   *
   * <code>optional double preprocessor_zero_tolerance = 39 [default = 1e-09];</code>
   * @return The preprocessorZeroTolerance.
   */
  double getPreprocessorZeroTolerance();

  /**
   * <pre>
   * The solver will stop as soon as it has proven that the objective is smaller
   * than objective_lower_limit or greater than objective_upper_limit. Depending
   * on the simplex algorithm (primal or dual) and the optimization direction,
   * note that only one bound will be used at the time.
   *
   * Important: The solver does not add any tolerances to these values, and as
   * soon as the objective (as computed by the solver, so with some imprecision)
   * crosses one of these bounds (strictly), the search will stop. It is up to
   * the client to add any tolerance if needed.
   * </pre>
   *
   * <code>optional double objective_lower_limit = 40 [default = -inf];</code>
   * @return Whether the objectiveLowerLimit field is set.
   */
  boolean hasObjectiveLowerLimit();
  /**
   * <pre>
   * The solver will stop as soon as it has proven that the objective is smaller
   * than objective_lower_limit or greater than objective_upper_limit. Depending
   * on the simplex algorithm (primal or dual) and the optimization direction,
   * note that only one bound will be used at the time.
   *
   * Important: The solver does not add any tolerances to these values, and as
   * soon as the objective (as computed by the solver, so with some imprecision)
   * crosses one of these bounds (strictly), the search will stop. It is up to
   * the client to add any tolerance if needed.
   * </pre>
   *
   * <code>optional double objective_lower_limit = 40 [default = -inf];</code>
   * @return The objectiveLowerLimit.
   */
  double getObjectiveLowerLimit();

  /**
   * <code>optional double objective_upper_limit = 41 [default = inf];</code>
   * @return Whether the objectiveUpperLimit field is set.
   */
  boolean hasObjectiveUpperLimit();
  /**
   * <code>optional double objective_upper_limit = 41 [default = inf];</code>
   * @return The objectiveUpperLimit.
   */
  double getObjectiveUpperLimit();

  /**
   * <pre>
   * During a degenerate iteration, the more conservative approach is to do a
   * step of length zero (while shifting the bound of the leaving variable).
   * That is, the variable values are unchanged for the primal simplex or the
   * reduced cost are unchanged for the dual simplex. However, instead of doing
   * a step of length zero, it seems to be better on degenerate problems to do a
   * small positive step. This is what is recommended in the EXPAND procedure
   * described in:
   * P. E. Gill, W. Murray, M. A. Saunders, and M. H. Wright. "A practical anti-
   * cycling procedure for linearly constrained optimization".
   * Mathematical Programming, 45:437&#92;u2013474, 1989.
   *
   * Here, during a degenerate iteration we do a small positive step of this
   * factor times the primal (resp. dual) tolerance. In the primal simplex, this
   * may effectively push variable values (very slightly) further out of their
   * bounds (resp. reduced costs for the dual simplex).
   *
   * Setting this to zero reverts to the more conservative approach of a zero
   * step during degenerate iterations.
   * </pre>
   *
   * <code>optional double degenerate_ministep_factor = 42 [default = 0.01];</code>
   * @return Whether the degenerateMinistepFactor field is set.
   */
  boolean hasDegenerateMinistepFactor();
  /**
   * <pre>
   * During a degenerate iteration, the more conservative approach is to do a
   * step of length zero (while shifting the bound of the leaving variable).
   * That is, the variable values are unchanged for the primal simplex or the
   * reduced cost are unchanged for the dual simplex. However, instead of doing
   * a step of length zero, it seems to be better on degenerate problems to do a
   * small positive step. This is what is recommended in the EXPAND procedure
   * described in:
   * P. E. Gill, W. Murray, M. A. Saunders, and M. H. Wright. "A practical anti-
   * cycling procedure for linearly constrained optimization".
   * Mathematical Programming, 45:437&#92;u2013474, 1989.
   *
   * Here, during a degenerate iteration we do a small positive step of this
   * factor times the primal (resp. dual) tolerance. In the primal simplex, this
   * may effectively push variable values (very slightly) further out of their
   * bounds (resp. reduced costs for the dual simplex).
   *
   * Setting this to zero reverts to the more conservative approach of a zero
   * step during degenerate iterations.
   * </pre>
   *
   * <code>optional double degenerate_ministep_factor = 42 [default = 0.01];</code>
   * @return The degenerateMinistepFactor.
   */
  double getDegenerateMinistepFactor();

  /**
   * <pre>
   * At the beginning of each solve, the random number generator used in some
   * part of the solver is reinitialized to this seed. If you change the random
   * seed, the solver may make different choices during the solving process.
   * Note that this may lead to a different solution, for example a different
   * optimal basis.
   *
   * For some problems, the running time may vary a lot depending on small
   * change in the solving algorithm. Running the solver with different seeds
   * enables to have more robust benchmarks when evaluating new features.
   *
   * Also note that the solver is fully deterministic: two runs of the same
   * binary, on the same machine, on the exact same data and with the same
   * parameters will go through the exact same iterations. If they hit a time
   * limit, they might of course yield different results because one will have
   * advanced farther than the other.
   * </pre>
   *
   * <code>optional int32 random_seed = 43 [default = 1];</code>
   * @return Whether the randomSeed field is set.
   */
  boolean hasRandomSeed();
  /**
   * <pre>
   * At the beginning of each solve, the random number generator used in some
   * part of the solver is reinitialized to this seed. If you change the random
   * seed, the solver may make different choices during the solving process.
   * Note that this may lead to a different solution, for example a different
   * optimal basis.
   *
   * For some problems, the running time may vary a lot depending on small
   * change in the solving algorithm. Running the solver with different seeds
   * enables to have more robust benchmarks when evaluating new features.
   *
   * Also note that the solver is fully deterministic: two runs of the same
   * binary, on the same machine, on the exact same data and with the same
   * parameters will go through the exact same iterations. If they hit a time
   * limit, they might of course yield different results because one will have
   * advanced farther than the other.
   * </pre>
   *
   * <code>optional int32 random_seed = 43 [default = 1];</code>
   * @return The randomSeed.
   */
  int getRandomSeed();

  /**
   * <pre>
   * Number of threads in the OMP parallel sections. If left to 1, the code will
   * not create any OMP threads and will remain single-threaded.
   * </pre>
   *
   * <code>optional int32 num_omp_threads = 44 [default = 1];</code>
   * @return Whether the numOmpThreads field is set.
   */
  boolean hasNumOmpThreads();
  /**
   * <pre>
   * Number of threads in the OMP parallel sections. If left to 1, the code will
   * not create any OMP threads and will remain single-threaded.
   * </pre>
   *
   * <code>optional int32 num_omp_threads = 44 [default = 1];</code>
   * @return The numOmpThreads.
   */
  int getNumOmpThreads();

  /**
   * <pre>
   * When this is true, then the costs are randomly perturbed before the dual
   * simplex is even started. This has been shown to improve the dual simplex
   * performance. For a good reference, see Huangfu Q (2013) "High performance
   * simplex solver", Ph.D, dissertation, University of Edinburgh.
   * </pre>
   *
   * <code>optional bool perturb_costs_in_dual_simplex = 53 [default = false];</code>
   * @return Whether the perturbCostsInDualSimplex field is set.
   */
  boolean hasPerturbCostsInDualSimplex();
  /**
   * <pre>
   * When this is true, then the costs are randomly perturbed before the dual
   * simplex is even started. This has been shown to improve the dual simplex
   * performance. For a good reference, see Huangfu Q (2013) "High performance
   * simplex solver", Ph.D, dissertation, University of Edinburgh.
   * </pre>
   *
   * <code>optional bool perturb_costs_in_dual_simplex = 53 [default = false];</code>
   * @return The perturbCostsInDualSimplex.
   */
  boolean getPerturbCostsInDualSimplex();

  /**
   * <pre>
   * We have two possible dual phase I algorithms. Both work on an LP that
   * minimize the sum of dual infeasiblities. One use dedicated code (when this
   * param is true), the other one use exactly the same code as the dual phase
   * II but on an auxiliary problem where the variable bounds of the original
   * problem are changed.
   *
   * TODO(user): For now we have both, but ideally the non-dedicated version
   * will win since it is a lot less code to maintain.
   * </pre>
   *
   * <code>optional bool use_dedicated_dual_feasibility_algorithm = 62 [default = true];</code>
   * @return Whether the useDedicatedDualFeasibilityAlgorithm field is set.
   */
  boolean hasUseDedicatedDualFeasibilityAlgorithm();
  /**
   * <pre>
   * We have two possible dual phase I algorithms. Both work on an LP that
   * minimize the sum of dual infeasiblities. One use dedicated code (when this
   * param is true), the other one use exactly the same code as the dual phase
   * II but on an auxiliary problem where the variable bounds of the original
   * problem are changed.
   *
   * TODO(user): For now we have both, but ideally the non-dedicated version
   * will win since it is a lot less code to maintain.
   * </pre>
   *
   * <code>optional bool use_dedicated_dual_feasibility_algorithm = 62 [default = true];</code>
   * @return The useDedicatedDualFeasibilityAlgorithm.
   */
  boolean getUseDedicatedDualFeasibilityAlgorithm();

  /**
   * <pre>
   * The magnitude of the cost perturbation is given by
   * RandomIn(1.0, 2.0) * (
   * relative_cost_perturbation * cost
   * + relative_max_cost_perturbation * max_cost);
   * </pre>
   *
   * <code>optional double relative_cost_perturbation = 54 [default = 1e-05];</code>
   * @return Whether the relativeCostPerturbation field is set.
   */
  boolean hasRelativeCostPerturbation();
  /**
   * <pre>
   * The magnitude of the cost perturbation is given by
   * RandomIn(1.0, 2.0) * (
   * relative_cost_perturbation * cost
   * + relative_max_cost_perturbation * max_cost);
   * </pre>
   *
   * <code>optional double relative_cost_perturbation = 54 [default = 1e-05];</code>
   * @return The relativeCostPerturbation.
   */
  double getRelativeCostPerturbation();

  /**
   * <code>optional double relative_max_cost_perturbation = 55 [default = 1e-07];</code>
   * @return Whether the relativeMaxCostPerturbation field is set.
   */
  boolean hasRelativeMaxCostPerturbation();
  /**
   * <code>optional double relative_max_cost_perturbation = 55 [default = 1e-07];</code>
   * @return The relativeMaxCostPerturbation.
   */
  double getRelativeMaxCostPerturbation();

  /**
   * <pre>
   * If our upper bound on the condition number of the initial basis (from our
   * heurisitic or a warm start) is above this threshold, we revert to an all
   * slack basis.
   * </pre>
   *
   * <code>optional double initial_condition_number_threshold = 59 [default = 1e+50];</code>
   * @return Whether the initialConditionNumberThreshold field is set.
   */
  boolean hasInitialConditionNumberThreshold();
  /**
   * <pre>
   * If our upper bound on the condition number of the initial basis (from our
   * heurisitic or a warm start) is above this threshold, we revert to an all
   * slack basis.
   * </pre>
   *
   * <code>optional double initial_condition_number_threshold = 59 [default = 1e+50];</code>
   * @return The initialConditionNumberThreshold.
   */
  double getInitialConditionNumberThreshold();

  /**
   * <pre>
   * If true, logs the progress of a solve to LOG(INFO). Note that the same
   * messages can also be turned on by displaying logs at level 1 for the
   * relevant files.
   * </pre>
   *
   * <code>optional bool log_search_progress = 61 [default = false];</code>
   * @return Whether the logSearchProgress field is set.
   */
  boolean hasLogSearchProgress();
  /**
   * <pre>
   * If true, logs the progress of a solve to LOG(INFO). Note that the same
   * messages can also be turned on by displaying logs at level 1 for the
   * relevant files.
   * </pre>
   *
   * <code>optional bool log_search_progress = 61 [default = false];</code>
   * @return The logSearchProgress.
   */
  boolean getLogSearchProgress();

  /**
   * <pre>
   * If true, logs will be displayed to stdout instead of using Google log info.
   * </pre>
   *
   * <code>optional bool log_to_stdout = 66 [default = true];</code>
   * @return Whether the logToStdout field is set.
   */
  boolean hasLogToStdout();
  /**
   * <pre>
   * If true, logs will be displayed to stdout instead of using Google log info.
   * </pre>
   *
   * <code>optional bool log_to_stdout = 66 [default = true];</code>
   * @return The logToStdout.
   */
  boolean getLogToStdout();

  /**
   * <pre>
   * If the starting basis contains FREE variable with bounds, we will move
   * any such variable to their closer bounds if the distance is smaller than
   * this parameter.
   *
   * The starting statuses can contains FREE variables with bounds, if a user
   * set it like this externally. Also, any variable with an initial BASIC
   * status that was not kept in the initial basis is marked as FREE before this
   * step is applied.
   *
   * Note that by default a FREE variable is assumed to be zero unless a
   * starting value was specified via SetStartingVariableValuesForNextSolve().
   *
   * Note that, at the end of the solve, some of these FREE variable with bounds
   * and an interior point value might still be left in the final solution.
   * Enable push_to_vertex to clean these up.
   * </pre>
   *
   * <code>optional double crossover_bound_snapping_distance = 64 [default = inf];</code>
   * @return Whether the crossoverBoundSnappingDistance field is set.
   */
  boolean hasCrossoverBoundSnappingDistance();
  /**
   * <pre>
   * If the starting basis contains FREE variable with bounds, we will move
   * any such variable to their closer bounds if the distance is smaller than
   * this parameter.
   *
   * The starting statuses can contains FREE variables with bounds, if a user
   * set it like this externally. Also, any variable with an initial BASIC
   * status that was not kept in the initial basis is marked as FREE before this
   * step is applied.
   *
   * Note that by default a FREE variable is assumed to be zero unless a
   * starting value was specified via SetStartingVariableValuesForNextSolve().
   *
   * Note that, at the end of the solve, some of these FREE variable with bounds
   * and an interior point value might still be left in the final solution.
   * Enable push_to_vertex to clean these up.
   * </pre>
   *
   * <code>optional double crossover_bound_snapping_distance = 64 [default = inf];</code>
   * @return The crossoverBoundSnappingDistance.
   */
  double getCrossoverBoundSnappingDistance();

  /**
   * <pre>
   * If the optimization phases finishes with super-basic variables (i.e.,
   * variables that either 1) have bounds but are FREE in the basis, or 2) have
   * no bounds and are FREE in the basis at a nonzero value), then run a "push"
   * phase to push these variables to bounds, obtaining a vertex solution. Note
   * this situation can happen only if a starting value was specified via
   * SetStartingVariableValuesForNextSolve().
   * </pre>
   *
   * <code>optional bool push_to_vertex = 65 [default = true];</code>
   * @return Whether the pushToVertex field is set.
   */
  boolean hasPushToVertex();
  /**
   * <pre>
   * If the optimization phases finishes with super-basic variables (i.e.,
   * variables that either 1) have bounds but are FREE in the basis, or 2) have
   * no bounds and are FREE in the basis at a nonzero value), then run a "push"
   * phase to push these variables to bounds, obtaining a vertex solution. Note
   * this situation can happen only if a starting value was specified via
   * SetStartingVariableValuesForNextSolve().
   * </pre>
   *
   * <code>optional bool push_to_vertex = 65 [default = true];</code>
   * @return The pushToVertex.
   */
  boolean getPushToVertex();

  /**
   * <pre>
   * If presolve runs, include the pass that detects implied free variables.
   * </pre>
   *
   * <code>optional bool use_implied_free_preprocessor = 67 [default = true];</code>
   * @return Whether the useImpliedFreePreprocessor field is set.
   */
  boolean hasUseImpliedFreePreprocessor();
  /**
   * <pre>
   * If presolve runs, include the pass that detects implied free variables.
   * </pre>
   *
   * <code>optional bool use_implied_free_preprocessor = 67 [default = true];</code>
   * @return The useImpliedFreePreprocessor.
   */
  boolean getUseImpliedFreePreprocessor();

  /**
   * <pre>
   * Any finite values in the input LP must be below this threshold, otherwise
   * the model will be reported invalid. This is needed to avoid floating point
   * overflow when evaluating bounds * coeff for instance. In practice, users
   * shouldn't use super large values in an LP. With the default threshold, even
   * evaluating large constraint with variables at their bound shouldn't cause
   * any overflow.
   * </pre>
   *
   * <code>optional double max_valid_magnitude = 70 [default = 1e+30];</code>
   * @return Whether the maxValidMagnitude field is set.
   */
  boolean hasMaxValidMagnitude();
  /**
   * <pre>
   * Any finite values in the input LP must be below this threshold, otherwise
   * the model will be reported invalid. This is needed to avoid floating point
   * overflow when evaluating bounds * coeff for instance. In practice, users
   * shouldn't use super large values in an LP. With the default threshold, even
   * evaluating large constraint with variables at their bound shouldn't cause
   * any overflow.
   * </pre>
   *
   * <code>optional double max_valid_magnitude = 70 [default = 1e+30];</code>
   * @return The maxValidMagnitude.
   */
  double getMaxValidMagnitude();

  /**
   * <pre>
   * Value in the input LP lower than this will be ignored. This is similar to
   * drop_tolerance but more aggressive as this is used before scaling. This is
   * mainly here to avoid underflow and have simpler invariant in the code, like
   * a * b == 0 iff a or b is zero and things like this.
   * </pre>
   *
   * <code>optional double drop_magnitude = 71 [default = 1e-30];</code>
   * @return Whether the dropMagnitude field is set.
   */
  boolean hasDropMagnitude();
  /**
   * <pre>
   * Value in the input LP lower than this will be ignored. This is similar to
   * drop_tolerance but more aggressive as this is used before scaling. This is
   * mainly here to avoid underflow and have simpler invariant in the code, like
   * a * b == 0 iff a or b is zero and things like this.
   * </pre>
   *
   * <code>optional double drop_magnitude = 71 [default = 1e-30];</code>
   * @return The dropMagnitude.
   */
  double getDropMagnitude();

  /**
   * <pre>
   * On some problem like stp3d or pds-100 this makes a huge difference in
   * speed and number of iterations of the dual simplex.
   * </pre>
   *
   * <code>optional bool dual_price_prioritize_norm = 69 [default = false];</code>
   * @return Whether the dualPricePrioritizeNorm field is set.
   */
  boolean hasDualPricePrioritizeNorm();
  /**
   * <pre>
   * On some problem like stp3d or pds-100 this makes a huge difference in
   * speed and number of iterations of the dual simplex.
   * </pre>
   *
   * <code>optional bool dual_price_prioritize_norm = 69 [default = false];</code>
   * @return The dualPricePrioritizeNorm.
   */
  boolean getDualPricePrioritizeNorm();
}
