// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/algorithms/set_cover.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.algorithms;

/**
 * Protobuf type {@code operations_research.SetCoverSolutionResponse}
 */
public final class SetCoverSolutionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:operations_research.SetCoverSolutionResponse)
    SetCoverSolutionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      SetCoverSolutionResponse.class.getName());
  }
  // Use SetCoverSolutionResponse.newBuilder() to construct.
  private SetCoverSolutionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SetCoverSolutionResponse() {
    status_ = 0;
    subset_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ortools.algorithms.SetCover.internal_static_operations_research_SetCoverSolutionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ortools.algorithms.SetCover.internal_static_operations_research_SetCoverSolutionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ortools.algorithms.SetCoverSolutionResponse.class, com.google.ortools.algorithms.SetCoverSolutionResponse.Builder.class);
  }

  /**
   * <pre>
   * Result of the optimization.
   * </pre>
   *
   * Protobuf enum {@code operations_research.SetCoverSolutionResponse.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Undefined.
     * </pre>
     *
     * <code>UNDEFINED = 0;</code>
     */
    UNDEFINED(0),
    /**
     * <pre>
     * The solver found the proven optimal solution.
     * </pre>
     *
     * <code>OPTIMAL = 1;</code>
     */
    OPTIMAL(1),
    /**
     * <pre>
     * The solver had enough time to find some solution that satisfied all
     * constraints, but it did not reach the optimal.
     * </pre>
     *
     * <code>FEASIBLE = 2;</code>
     */
    FEASIBLE(2),
    /**
     * <pre>
     * The model does not have any solution.
     * </pre>
     *
     * <code>INFEASIBLE = 3;</code>
     */
    INFEASIBLE(3),
    /**
     * <pre>
     * The model is invalid.
     * </pre>
     *
     * <code>INVALID = 4;</code>
     */
    INVALID(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Status.class.getName());
    }
    /**
     * <pre>
     * Undefined.
     * </pre>
     *
     * <code>UNDEFINED = 0;</code>
     */
    public static final int UNDEFINED_VALUE = 0;
    /**
     * <pre>
     * The solver found the proven optimal solution.
     * </pre>
     *
     * <code>OPTIMAL = 1;</code>
     */
    public static final int OPTIMAL_VALUE = 1;
    /**
     * <pre>
     * The solver had enough time to find some solution that satisfied all
     * constraints, but it did not reach the optimal.
     * </pre>
     *
     * <code>FEASIBLE = 2;</code>
     */
    public static final int FEASIBLE_VALUE = 2;
    /**
     * <pre>
     * The model does not have any solution.
     * </pre>
     *
     * <code>INFEASIBLE = 3;</code>
     */
    public static final int INFEASIBLE_VALUE = 3;
    /**
     * <pre>
     * The model is invalid.
     * </pre>
     *
     * <code>INVALID = 4;</code>
     */
    public static final int INVALID_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Status forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED;
        case 1: return OPTIMAL;
        case 2: return FEASIBLE;
        case 3: return INFEASIBLE;
        case 4: return INVALID;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.ortools.algorithms.SetCoverSolutionResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:operations_research.SetCoverSolutionResponse.Status)
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 0;
  /**
   * <pre>
   * For future use. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * For future use. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * For future use. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override public com.google.ortools.algorithms.SetCoverSolutionResponse.Status getStatus() {
    com.google.ortools.algorithms.SetCoverSolutionResponse.Status result = com.google.ortools.algorithms.SetCoverSolutionResponse.Status.forNumber(status_);
    return result == null ? com.google.ortools.algorithms.SetCoverSolutionResponse.Status.UNRECOGNIZED : result;
  }

  public static final int NUM_SUBSETS_FIELD_NUMBER = 2;
  private int numSubsets_ = 0;
  /**
   * <pre>
   * The number of subsets that are selected in the solution. This is used
   * to decompress their indices below.
   * </pre>
   *
   * <code>optional int32 num_subsets = 2;</code>
   * @return Whether the numSubsets field is set.
   */
  @java.lang.Override
  public boolean hasNumSubsets() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The number of subsets that are selected in the solution. This is used
   * to decompress their indices below.
   * </pre>
   *
   * <code>optional int32 num_subsets = 2;</code>
   * @return The numSubsets.
   */
  @java.lang.Override
  public int getNumSubsets() {
    return numSubsets_;
  }

  public static final int SUBSET_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList subset_ =
      emptyIntList();
  /**
   * <pre>
   * The list of the subsets selected in the solution.
   * </pre>
   *
   * <code>repeated int32 subset = 3 [packed = true];</code>
   * @return A list containing the subset.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getSubsetList() {
    return subset_;
  }
  /**
   * <pre>
   * The list of the subsets selected in the solution.
   * </pre>
   *
   * <code>repeated int32 subset = 3 [packed = true];</code>
   * @return The count of subset.
   */
  public int getSubsetCount() {
    return subset_.size();
  }
  /**
   * <pre>
   * The list of the subsets selected in the solution.
   * </pre>
   *
   * <code>repeated int32 subset = 3 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The subset at the given index.
   */
  public int getSubset(int index) {
    return subset_.getInt(index);
  }
  private int subsetMemoizedSerializedSize = -1;

  public static final int COST_FIELD_NUMBER = 4;
  private double cost_ = 0D;
  /**
   * <pre>
   * The cost of the solution, as computed by the algorithm.
   * </pre>
   *
   * <code>optional double cost = 4;</code>
   * @return Whether the cost field is set.
   */
  @java.lang.Override
  public boolean hasCost() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The cost of the solution, as computed by the algorithm.
   * </pre>
   *
   * <code>optional double cost = 4;</code>
   * @return The cost.
   */
  @java.lang.Override
  public double getCost() {
    return cost_;
  }

  public static final int COST_LOWER_BOUND_FIELD_NUMBER = 5;
  private double costLowerBound_ = 0D;
  /**
   * <pre>
   * A lower bound of the solution, as computed by the algorithm.
   * </pre>
   *
   * <code>optional double cost_lower_bound = 5;</code>
   * @return Whether the costLowerBound field is set.
   */
  @java.lang.Override
  public boolean hasCostLowerBound() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * A lower bound of the solution, as computed by the algorithm.
   * </pre>
   *
   * <code>optional double cost_lower_bound = 5;</code>
   * @return The costLowerBound.
   */
  @java.lang.Override
  public double getCostLowerBound() {
    return costLowerBound_;
  }

  public static final int FINGERPRINT_FIELD_NUMBER = 6;
  private com.google.ortools.util.Int128 fingerprint_;
  /**
   * <pre>
   * An automatically fingerprint for the solution. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.Int128 fingerprint = 6;</code>
   * @return Whether the fingerprint field is set.
   */
  @java.lang.Override
  public boolean hasFingerprint() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * An automatically fingerprint for the solution. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.Int128 fingerprint = 6;</code>
   * @return The fingerprint.
   */
  @java.lang.Override
  public com.google.ortools.util.Int128 getFingerprint() {
    return fingerprint_ == null ? com.google.ortools.util.Int128.getDefaultInstance() : fingerprint_;
  }
  /**
   * <pre>
   * An automatically fingerprint for the solution. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.Int128 fingerprint = 6;</code>
   */
  @java.lang.Override
  public com.google.ortools.util.Int128OrBuilder getFingerprintOrBuilder() {
    return fingerprint_ == null ? com.google.ortools.util.Int128.getDefaultInstance() : fingerprint_;
  }

  public static final int MODEL_FINGERPRINT_FIELD_NUMBER = 7;
  private com.google.ortools.util.Int128 modelFingerprint_;
  /**
   * <pre>
   * A reference to the model the solution applies to. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
   * @return Whether the modelFingerprint field is set.
   */
  @java.lang.Override
  public boolean hasModelFingerprint() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * A reference to the model the solution applies to. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
   * @return The modelFingerprint.
   */
  @java.lang.Override
  public com.google.ortools.util.Int128 getModelFingerprint() {
    return modelFingerprint_ == null ? com.google.ortools.util.Int128.getDefaultInstance() : modelFingerprint_;
  }
  /**
   * <pre>
   * A reference to the model the solution applies to. TODO(user): Implement.
   * </pre>
   *
   * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
   */
  @java.lang.Override
  public com.google.ortools.util.Int128OrBuilder getModelFingerprintOrBuilder() {
    return modelFingerprint_ == null ? com.google.ortools.util.Int128.getDefaultInstance() : modelFingerprint_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, status_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, numSubsets_);
    }
    if (getSubsetList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(subsetMemoizedSerializedSize);
    }
    for (int i = 0; i < subset_.size(); i++) {
      output.writeInt32NoTag(subset_.getInt(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeDouble(4, cost_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeDouble(5, costLowerBound_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(6, getFingerprint());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(7, getModelFingerprint());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numSubsets_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < subset_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(subset_.getInt(i));
      }
      size += dataSize;
      if (!getSubsetList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      subsetMemoizedSerializedSize = dataSize;
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, cost_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, costLowerBound_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getFingerprint());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getModelFingerprint());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ortools.algorithms.SetCoverSolutionResponse)) {
      return super.equals(obj);
    }
    com.google.ortools.algorithms.SetCoverSolutionResponse other = (com.google.ortools.algorithms.SetCoverSolutionResponse) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (status_ != other.status_) return false;
    }
    if (hasNumSubsets() != other.hasNumSubsets()) return false;
    if (hasNumSubsets()) {
      if (getNumSubsets()
          != other.getNumSubsets()) return false;
    }
    if (!getSubsetList()
        .equals(other.getSubsetList())) return false;
    if (hasCost() != other.hasCost()) return false;
    if (hasCost()) {
      if (java.lang.Double.doubleToLongBits(getCost())
          != java.lang.Double.doubleToLongBits(
              other.getCost())) return false;
    }
    if (hasCostLowerBound() != other.hasCostLowerBound()) return false;
    if (hasCostLowerBound()) {
      if (java.lang.Double.doubleToLongBits(getCostLowerBound())
          != java.lang.Double.doubleToLongBits(
              other.getCostLowerBound())) return false;
    }
    if (hasFingerprint() != other.hasFingerprint()) return false;
    if (hasFingerprint()) {
      if (!getFingerprint()
          .equals(other.getFingerprint())) return false;
    }
    if (hasModelFingerprint() != other.hasModelFingerprint()) return false;
    if (hasModelFingerprint()) {
      if (!getModelFingerprint()
          .equals(other.getModelFingerprint())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
    }
    if (hasNumSubsets()) {
      hash = (37 * hash) + NUM_SUBSETS_FIELD_NUMBER;
      hash = (53 * hash) + getNumSubsets();
    }
    if (getSubsetCount() > 0) {
      hash = (37 * hash) + SUBSET_FIELD_NUMBER;
      hash = (53 * hash) + getSubsetList().hashCode();
    }
    if (hasCost()) {
      hash = (37 * hash) + COST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCost()));
    }
    if (hasCostLowerBound()) {
      hash = (37 * hash) + COST_LOWER_BOUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCostLowerBound()));
    }
    if (hasFingerprint()) {
      hash = (37 * hash) + FINGERPRINT_FIELD_NUMBER;
      hash = (53 * hash) + getFingerprint().hashCode();
    }
    if (hasModelFingerprint()) {
      hash = (37 * hash) + MODEL_FINGERPRINT_FIELD_NUMBER;
      hash = (53 * hash) + getModelFingerprint().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ortools.algorithms.SetCoverSolutionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ortools.algorithms.SetCoverSolutionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code operations_research.SetCoverSolutionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:operations_research.SetCoverSolutionResponse)
      com.google.ortools.algorithms.SetCoverSolutionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ortools.algorithms.SetCover.internal_static_operations_research_SetCoverSolutionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ortools.algorithms.SetCover.internal_static_operations_research_SetCoverSolutionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ortools.algorithms.SetCoverSolutionResponse.class, com.google.ortools.algorithms.SetCoverSolutionResponse.Builder.class);
    }

    // Construct using com.google.ortools.algorithms.SetCoverSolutionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getFingerprintFieldBuilder();
        getModelFingerprintFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      numSubsets_ = 0;
      subset_ = emptyIntList();
      cost_ = 0D;
      costLowerBound_ = 0D;
      fingerprint_ = null;
      if (fingerprintBuilder_ != null) {
        fingerprintBuilder_.dispose();
        fingerprintBuilder_ = null;
      }
      modelFingerprint_ = null;
      if (modelFingerprintBuilder_ != null) {
        modelFingerprintBuilder_.dispose();
        modelFingerprintBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ortools.algorithms.SetCover.internal_static_operations_research_SetCoverSolutionResponse_descriptor;
    }

    @java.lang.Override
    public com.google.ortools.algorithms.SetCoverSolutionResponse getDefaultInstanceForType() {
      return com.google.ortools.algorithms.SetCoverSolutionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ortools.algorithms.SetCoverSolutionResponse build() {
      com.google.ortools.algorithms.SetCoverSolutionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ortools.algorithms.SetCoverSolutionResponse buildPartial() {
      com.google.ortools.algorithms.SetCoverSolutionResponse result = new com.google.ortools.algorithms.SetCoverSolutionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.ortools.algorithms.SetCoverSolutionResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.numSubsets_ = numSubsets_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        subset_.makeImmutable();
        result.subset_ = subset_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cost_ = cost_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.costLowerBound_ = costLowerBound_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.fingerprint_ = fingerprintBuilder_ == null
            ? fingerprint_
            : fingerprintBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.modelFingerprint_ = modelFingerprintBuilder_ == null
            ? modelFingerprint_
            : modelFingerprintBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ortools.algorithms.SetCoverSolutionResponse) {
        return mergeFrom((com.google.ortools.algorithms.SetCoverSolutionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ortools.algorithms.SetCoverSolutionResponse other) {
      if (other == com.google.ortools.algorithms.SetCoverSolutionResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      if (other.hasNumSubsets()) {
        setNumSubsets(other.getNumSubsets());
      }
      if (!other.subset_.isEmpty()) {
        if (subset_.isEmpty()) {
          subset_ = other.subset_;
          subset_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureSubsetIsMutable();
          subset_.addAll(other.subset_);
        }
        onChanged();
      }
      if (other.hasCost()) {
        setCost(other.getCost());
      }
      if (other.hasCostLowerBound()) {
        setCostLowerBound(other.getCostLowerBound());
      }
      if (other.hasFingerprint()) {
        mergeFingerprint(other.getFingerprint());
      }
      if (other.hasModelFingerprint()) {
        mergeModelFingerprint(other.getModelFingerprint());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              numSubsets_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              int v = input.readInt32();
              ensureSubsetIsMutable();
              subset_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureSubsetIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                subset_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 33: {
              cost_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              costLowerBound_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 50: {
              input.readMessage(
                  getFingerprintFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getModelFingerprintFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <pre>
     * For future use. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * For future use. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * For future use. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For future use. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.google.ortools.algorithms.SetCoverSolutionResponse.Status getStatus() {
      com.google.ortools.algorithms.SetCoverSolutionResponse.Status result = com.google.ortools.algorithms.SetCoverSolutionResponse.Status.forNumber(status_);
      return result == null ? com.google.ortools.algorithms.SetCoverSolutionResponse.Status.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * For future use. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.google.ortools.algorithms.SetCoverSolutionResponse.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For future use. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.SetCoverSolutionResponse.Status status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private int numSubsets_ ;
    /**
     * <pre>
     * The number of subsets that are selected in the solution. This is used
     * to decompress their indices below.
     * </pre>
     *
     * <code>optional int32 num_subsets = 2;</code>
     * @return Whether the numSubsets field is set.
     */
    @java.lang.Override
    public boolean hasNumSubsets() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The number of subsets that are selected in the solution. This is used
     * to decompress their indices below.
     * </pre>
     *
     * <code>optional int32 num_subsets = 2;</code>
     * @return The numSubsets.
     */
    @java.lang.Override
    public int getNumSubsets() {
      return numSubsets_;
    }
    /**
     * <pre>
     * The number of subsets that are selected in the solution. This is used
     * to decompress their indices below.
     * </pre>
     *
     * <code>optional int32 num_subsets = 2;</code>
     * @param value The numSubsets to set.
     * @return This builder for chaining.
     */
    public Builder setNumSubsets(int value) {

      numSubsets_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of subsets that are selected in the solution. This is used
     * to decompress their indices below.
     * </pre>
     *
     * <code>optional int32 num_subsets = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumSubsets() {
      bitField0_ = (bitField0_ & ~0x00000002);
      numSubsets_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList subset_ = emptyIntList();
    private void ensureSubsetIsMutable() {
      if (!subset_.isModifiable()) {
        subset_ = makeMutableCopy(subset_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * The list of the subsets selected in the solution.
     * </pre>
     *
     * <code>repeated int32 subset = 3 [packed = true];</code>
     * @return A list containing the subset.
     */
    public java.util.List<java.lang.Integer>
        getSubsetList() {
      subset_.makeImmutable();
      return subset_;
    }
    /**
     * <pre>
     * The list of the subsets selected in the solution.
     * </pre>
     *
     * <code>repeated int32 subset = 3 [packed = true];</code>
     * @return The count of subset.
     */
    public int getSubsetCount() {
      return subset_.size();
    }
    /**
     * <pre>
     * The list of the subsets selected in the solution.
     * </pre>
     *
     * <code>repeated int32 subset = 3 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The subset at the given index.
     */
    public int getSubset(int index) {
      return subset_.getInt(index);
    }
    /**
     * <pre>
     * The list of the subsets selected in the solution.
     * </pre>
     *
     * <code>repeated int32 subset = 3 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The subset to set.
     * @return This builder for chaining.
     */
    public Builder setSubset(
        int index, int value) {

      ensureSubsetIsMutable();
      subset_.setInt(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The list of the subsets selected in the solution.
     * </pre>
     *
     * <code>repeated int32 subset = 3 [packed = true];</code>
     * @param value The subset to add.
     * @return This builder for chaining.
     */
    public Builder addSubset(int value) {

      ensureSubsetIsMutable();
      subset_.addInt(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The list of the subsets selected in the solution.
     * </pre>
     *
     * <code>repeated int32 subset = 3 [packed = true];</code>
     * @param values The subset to add.
     * @return This builder for chaining.
     */
    public Builder addAllSubset(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureSubsetIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, subset_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The list of the subsets selected in the solution.
     * </pre>
     *
     * <code>repeated int32 subset = 3 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubset() {
      subset_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private double cost_ ;
    /**
     * <pre>
     * The cost of the solution, as computed by the algorithm.
     * </pre>
     *
     * <code>optional double cost = 4;</code>
     * @return Whether the cost field is set.
     */
    @java.lang.Override
    public boolean hasCost() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * The cost of the solution, as computed by the algorithm.
     * </pre>
     *
     * <code>optional double cost = 4;</code>
     * @return The cost.
     */
    @java.lang.Override
    public double getCost() {
      return cost_;
    }
    /**
     * <pre>
     * The cost of the solution, as computed by the algorithm.
     * </pre>
     *
     * <code>optional double cost = 4;</code>
     * @param value The cost to set.
     * @return This builder for chaining.
     */
    public Builder setCost(double value) {

      cost_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The cost of the solution, as computed by the algorithm.
     * </pre>
     *
     * <code>optional double cost = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCost() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cost_ = 0D;
      onChanged();
      return this;
    }

    private double costLowerBound_ ;
    /**
     * <pre>
     * A lower bound of the solution, as computed by the algorithm.
     * </pre>
     *
     * <code>optional double cost_lower_bound = 5;</code>
     * @return Whether the costLowerBound field is set.
     */
    @java.lang.Override
    public boolean hasCostLowerBound() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * A lower bound of the solution, as computed by the algorithm.
     * </pre>
     *
     * <code>optional double cost_lower_bound = 5;</code>
     * @return The costLowerBound.
     */
    @java.lang.Override
    public double getCostLowerBound() {
      return costLowerBound_;
    }
    /**
     * <pre>
     * A lower bound of the solution, as computed by the algorithm.
     * </pre>
     *
     * <code>optional double cost_lower_bound = 5;</code>
     * @param value The costLowerBound to set.
     * @return This builder for chaining.
     */
    public Builder setCostLowerBound(double value) {

      costLowerBound_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A lower bound of the solution, as computed by the algorithm.
     * </pre>
     *
     * <code>optional double cost_lower_bound = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCostLowerBound() {
      bitField0_ = (bitField0_ & ~0x00000010);
      costLowerBound_ = 0D;
      onChanged();
      return this;
    }

    private com.google.ortools.util.Int128 fingerprint_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.ortools.util.Int128, com.google.ortools.util.Int128.Builder, com.google.ortools.util.Int128OrBuilder> fingerprintBuilder_;
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     * @return Whether the fingerprint field is set.
     */
    public boolean hasFingerprint() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     * @return The fingerprint.
     */
    public com.google.ortools.util.Int128 getFingerprint() {
      if (fingerprintBuilder_ == null) {
        return fingerprint_ == null ? com.google.ortools.util.Int128.getDefaultInstance() : fingerprint_;
      } else {
        return fingerprintBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     */
    public Builder setFingerprint(com.google.ortools.util.Int128 value) {
      if (fingerprintBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fingerprint_ = value;
      } else {
        fingerprintBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     */
    public Builder setFingerprint(
        com.google.ortools.util.Int128.Builder builderForValue) {
      if (fingerprintBuilder_ == null) {
        fingerprint_ = builderForValue.build();
      } else {
        fingerprintBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     */
    public Builder mergeFingerprint(com.google.ortools.util.Int128 value) {
      if (fingerprintBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          fingerprint_ != null &&
          fingerprint_ != com.google.ortools.util.Int128.getDefaultInstance()) {
          getFingerprintBuilder().mergeFrom(value);
        } else {
          fingerprint_ = value;
        }
      } else {
        fingerprintBuilder_.mergeFrom(value);
      }
      if (fingerprint_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     */
    public Builder clearFingerprint() {
      bitField0_ = (bitField0_ & ~0x00000020);
      fingerprint_ = null;
      if (fingerprintBuilder_ != null) {
        fingerprintBuilder_.dispose();
        fingerprintBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     */
    public com.google.ortools.util.Int128.Builder getFingerprintBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getFingerprintFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     */
    public com.google.ortools.util.Int128OrBuilder getFingerprintOrBuilder() {
      if (fingerprintBuilder_ != null) {
        return fingerprintBuilder_.getMessageOrBuilder();
      } else {
        return fingerprint_ == null ?
            com.google.ortools.util.Int128.getDefaultInstance() : fingerprint_;
      }
    }
    /**
     * <pre>
     * An automatically fingerprint for the solution. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 fingerprint = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.ortools.util.Int128, com.google.ortools.util.Int128.Builder, com.google.ortools.util.Int128OrBuilder> 
        getFingerprintFieldBuilder() {
      if (fingerprintBuilder_ == null) {
        fingerprintBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.ortools.util.Int128, com.google.ortools.util.Int128.Builder, com.google.ortools.util.Int128OrBuilder>(
                getFingerprint(),
                getParentForChildren(),
                isClean());
        fingerprint_ = null;
      }
      return fingerprintBuilder_;
    }

    private com.google.ortools.util.Int128 modelFingerprint_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.ortools.util.Int128, com.google.ortools.util.Int128.Builder, com.google.ortools.util.Int128OrBuilder> modelFingerprintBuilder_;
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     * @return Whether the modelFingerprint field is set.
     */
    public boolean hasModelFingerprint() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     * @return The modelFingerprint.
     */
    public com.google.ortools.util.Int128 getModelFingerprint() {
      if (modelFingerprintBuilder_ == null) {
        return modelFingerprint_ == null ? com.google.ortools.util.Int128.getDefaultInstance() : modelFingerprint_;
      } else {
        return modelFingerprintBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     */
    public Builder setModelFingerprint(com.google.ortools.util.Int128 value) {
      if (modelFingerprintBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modelFingerprint_ = value;
      } else {
        modelFingerprintBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     */
    public Builder setModelFingerprint(
        com.google.ortools.util.Int128.Builder builderForValue) {
      if (modelFingerprintBuilder_ == null) {
        modelFingerprint_ = builderForValue.build();
      } else {
        modelFingerprintBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     */
    public Builder mergeModelFingerprint(com.google.ortools.util.Int128 value) {
      if (modelFingerprintBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          modelFingerprint_ != null &&
          modelFingerprint_ != com.google.ortools.util.Int128.getDefaultInstance()) {
          getModelFingerprintBuilder().mergeFrom(value);
        } else {
          modelFingerprint_ = value;
        }
      } else {
        modelFingerprintBuilder_.mergeFrom(value);
      }
      if (modelFingerprint_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     */
    public Builder clearModelFingerprint() {
      bitField0_ = (bitField0_ & ~0x00000040);
      modelFingerprint_ = null;
      if (modelFingerprintBuilder_ != null) {
        modelFingerprintBuilder_.dispose();
        modelFingerprintBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     */
    public com.google.ortools.util.Int128.Builder getModelFingerprintBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getModelFingerprintFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     */
    public com.google.ortools.util.Int128OrBuilder getModelFingerprintOrBuilder() {
      if (modelFingerprintBuilder_ != null) {
        return modelFingerprintBuilder_.getMessageOrBuilder();
      } else {
        return modelFingerprint_ == null ?
            com.google.ortools.util.Int128.getDefaultInstance() : modelFingerprint_;
      }
    }
    /**
     * <pre>
     * A reference to the model the solution applies to. TODO(user): Implement.
     * </pre>
     *
     * <code>optional .operations_research.Int128 model_fingerprint = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.ortools.util.Int128, com.google.ortools.util.Int128.Builder, com.google.ortools.util.Int128OrBuilder> 
        getModelFingerprintFieldBuilder() {
      if (modelFingerprintBuilder_ == null) {
        modelFingerprintBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.ortools.util.Int128, com.google.ortools.util.Int128.Builder, com.google.ortools.util.Int128OrBuilder>(
                getModelFingerprint(),
                getParentForChildren(),
                isClean());
        modelFingerprint_ = null;
      }
      return modelFingerprintBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:operations_research.SetCoverSolutionResponse)
  }

  // @@protoc_insertion_point(class_scope:operations_research.SetCoverSolutionResponse)
  private static final com.google.ortools.algorithms.SetCoverSolutionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ortools.algorithms.SetCoverSolutionResponse();
  }

  public static com.google.ortools.algorithms.SetCoverSolutionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetCoverSolutionResponse>
      PARSER = new com.google.protobuf.AbstractParser<SetCoverSolutionResponse>() {
    @java.lang.Override
    public SetCoverSolutionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SetCoverSolutionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetCoverSolutionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ortools.algorithms.SetCoverSolutionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

