// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/sat/cp_model_service.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.sat.v1;

public interface CpSolverRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.sat.v1.CpSolverRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The model to solve.
   * </pre>
   *
   * <code>.operations_research.sat.CpModelProto model = 1;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <pre>
   * The model to solve.
   * </pre>
   *
   * <code>.operations_research.sat.CpModelProto model = 1;</code>
   * @return The model.
   */
  com.google.ortools.sat.CpModelProto getModel();
  /**
   * <pre>
   * The model to solve.
   * </pre>
   *
   * <code>.operations_research.sat.CpModelProto model = 1;</code>
   */
  com.google.ortools.sat.CpModelProtoOrBuilder getModelOrBuilder();

  /**
   * <pre>
   * Solver parameters.
   * </pre>
   *
   * <code>.operations_research.sat.SatParameters parameters = 3;</code>
   * @return Whether the parameters field is set.
   */
  boolean hasParameters();
  /**
   * <pre>
   * Solver parameters.
   * </pre>
   *
   * <code>.operations_research.sat.SatParameters parameters = 3;</code>
   * @return The parameters.
   */
  com.google.ortools.sat.SatParameters getParameters();
  /**
   * <pre>
   * Solver parameters.
   * </pre>
   *
   * <code>.operations_research.sat.SatParameters parameters = 3;</code>
   */
  com.google.ortools.sat.SatParametersOrBuilder getParametersOrBuilder();
}
