// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/graph/flow_problem.proto
// Protobuf Java Version: 4.26.1

package com.google.ortools.graph;

public final class FlowProblem {
  private FlowProblem() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      FlowProblem.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_FlowArcProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_operations_research_FlowArcProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_FlowNodeProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_operations_research_FlowNodeProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_FlowModelProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_operations_research_FlowModelProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n ortools/graph/flow_problem.proto\022\023oper" +
      "ations_research\"U\n\014FlowArcProto\022\014\n\004tail\030" +
      "\001 \001(\003\022\014\n\004head\030\002 \001(\003\022\023\n\010capacity\030\003 \001(\003:\0011" +
      "\022\024\n\tunit_cost\030\004 \001(\003:\0010\".\n\rFlowNodeProto\022" +
      "\n\n\002id\030\001 \001(\003\022\021\n\006supply\030\002 \001(\003:\0010\"\206\002\n\016FlowM" +
      "odelProto\0221\n\005nodes\030\001 \003(\0132\".operations_re" +
      "search.FlowNodeProto\022/\n\004arcs\030\002 \003(\0132!.ope" +
      "rations_research.FlowArcProto\022E\n\014problem" +
      "_type\030\003 \001(\0162/.operations_research.FlowMo" +
      "delProto.ProblemType\"I\n\013ProblemType\022\031\n\025L" +
      "INEAR_SUM_ASSIGNMENT\020\000\022\014\n\010MAX_FLOW\020\001\022\021\n\r" +
      "MIN_COST_FLOW\020\002B3\n\030com.google.ortools.gr" +
      "aphP\001\252\002\024Google.OrTools.Graph"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_operations_research_FlowArcProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_operations_research_FlowArcProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_operations_research_FlowArcProto_descriptor,
        new java.lang.String[] { "Tail", "Head", "Capacity", "UnitCost", });
    internal_static_operations_research_FlowNodeProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_operations_research_FlowNodeProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_operations_research_FlowNodeProto_descriptor,
        new java.lang.String[] { "Id", "Supply", });
    internal_static_operations_research_FlowModelProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_operations_research_FlowModelProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_operations_research_FlowModelProto_descriptor,
        new java.lang.String[] { "Nodes", "Arcs", "ProblemType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
