// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/bop/bop_parameters.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.bop;

/**
 * <pre>
 * Method used to optimize a solution in Bop.
 *
 * NEXT TAG: 16
 * </pre>
 *
 * Protobuf type {@code operations_research.bop.BopOptimizerMethod}
 */
public final class BopOptimizerMethod extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:operations_research.bop.BopOptimizerMethod)
    BopOptimizerMethodOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      BopOptimizerMethod.class.getName());
  }
  // Use BopOptimizerMethod.newBuilder() to construct.
  private BopOptimizerMethod(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BopOptimizerMethod() {
    type_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ortools.bop.BopParametersOuterClass.internal_static_operations_research_bop_BopOptimizerMethod_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ortools.bop.BopParametersOuterClass.internal_static_operations_research_bop_BopOptimizerMethod_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ortools.bop.BopOptimizerMethod.class, com.google.ortools.bop.BopOptimizerMethod.Builder.class);
  }

  /**
   * Protobuf enum {@code operations_research.bop.BopOptimizerMethod.OptimizerType}
   */
  public enum OptimizerType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SAT_CORE_BASED = 0;</code>
     */
    SAT_CORE_BASED(0),
    /**
     * <code>SAT_LINEAR_SEARCH = 15;</code>
     */
    SAT_LINEAR_SEARCH(15),
    /**
     * <code>LINEAR_RELAXATION = 1;</code>
     */
    LINEAR_RELAXATION(1),
    /**
     * <code>LOCAL_SEARCH = 2;</code>
     */
    LOCAL_SEARCH(2),
    /**
     * <code>RANDOM_FIRST_SOLUTION = 3;</code>
     */
    RANDOM_FIRST_SOLUTION(3),
    /**
     * <code>RANDOM_CONSTRAINT_LNS = 4;</code>
     */
    RANDOM_CONSTRAINT_LNS(4),
    /**
     * <code>RANDOM_VARIABLE_LNS = 5;</code>
     */
    RANDOM_VARIABLE_LNS(5),
    /**
     * <code>COMPLETE_LNS = 7;</code>
     */
    COMPLETE_LNS(7),
    /**
     * <code>LP_FIRST_SOLUTION = 8;</code>
     */
    LP_FIRST_SOLUTION(8),
    /**
     * <code>OBJECTIVE_FIRST_SOLUTION = 9;</code>
     */
    OBJECTIVE_FIRST_SOLUTION(9),
    /**
     * <code>USER_GUIDED_FIRST_SOLUTION = 14;</code>
     */
    USER_GUIDED_FIRST_SOLUTION(14),
    /**
     * <code>RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP = 11;</code>
     */
    RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP(11),
    /**
     * <code>RANDOM_VARIABLE_LNS_GUIDED_BY_LP = 12;</code>
     */
    RANDOM_VARIABLE_LNS_GUIDED_BY_LP(12),
    /**
     * <code>RELATION_GRAPH_LNS = 16;</code>
     */
    RELATION_GRAPH_LNS(16),
    /**
     * <code>RELATION_GRAPH_LNS_GUIDED_BY_LP = 17;</code>
     */
    RELATION_GRAPH_LNS_GUIDED_BY_LP(17),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        OptimizerType.class.getName());
    }
    /**
     * <code>SAT_CORE_BASED = 0;</code>
     */
    public static final int SAT_CORE_BASED_VALUE = 0;
    /**
     * <code>SAT_LINEAR_SEARCH = 15;</code>
     */
    public static final int SAT_LINEAR_SEARCH_VALUE = 15;
    /**
     * <code>LINEAR_RELAXATION = 1;</code>
     */
    public static final int LINEAR_RELAXATION_VALUE = 1;
    /**
     * <code>LOCAL_SEARCH = 2;</code>
     */
    public static final int LOCAL_SEARCH_VALUE = 2;
    /**
     * <code>RANDOM_FIRST_SOLUTION = 3;</code>
     */
    public static final int RANDOM_FIRST_SOLUTION_VALUE = 3;
    /**
     * <code>RANDOM_CONSTRAINT_LNS = 4;</code>
     */
    public static final int RANDOM_CONSTRAINT_LNS_VALUE = 4;
    /**
     * <code>RANDOM_VARIABLE_LNS = 5;</code>
     */
    public static final int RANDOM_VARIABLE_LNS_VALUE = 5;
    /**
     * <code>COMPLETE_LNS = 7;</code>
     */
    public static final int COMPLETE_LNS_VALUE = 7;
    /**
     * <code>LP_FIRST_SOLUTION = 8;</code>
     */
    public static final int LP_FIRST_SOLUTION_VALUE = 8;
    /**
     * <code>OBJECTIVE_FIRST_SOLUTION = 9;</code>
     */
    public static final int OBJECTIVE_FIRST_SOLUTION_VALUE = 9;
    /**
     * <code>USER_GUIDED_FIRST_SOLUTION = 14;</code>
     */
    public static final int USER_GUIDED_FIRST_SOLUTION_VALUE = 14;
    /**
     * <code>RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP = 11;</code>
     */
    public static final int RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP_VALUE = 11;
    /**
     * <code>RANDOM_VARIABLE_LNS_GUIDED_BY_LP = 12;</code>
     */
    public static final int RANDOM_VARIABLE_LNS_GUIDED_BY_LP_VALUE = 12;
    /**
     * <code>RELATION_GRAPH_LNS = 16;</code>
     */
    public static final int RELATION_GRAPH_LNS_VALUE = 16;
    /**
     * <code>RELATION_GRAPH_LNS_GUIDED_BY_LP = 17;</code>
     */
    public static final int RELATION_GRAPH_LNS_GUIDED_BY_LP_VALUE = 17;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OptimizerType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OptimizerType forNumber(int value) {
      switch (value) {
        case 0: return SAT_CORE_BASED;
        case 15: return SAT_LINEAR_SEARCH;
        case 1: return LINEAR_RELAXATION;
        case 2: return LOCAL_SEARCH;
        case 3: return RANDOM_FIRST_SOLUTION;
        case 4: return RANDOM_CONSTRAINT_LNS;
        case 5: return RANDOM_VARIABLE_LNS;
        case 7: return COMPLETE_LNS;
        case 8: return LP_FIRST_SOLUTION;
        case 9: return OBJECTIVE_FIRST_SOLUTION;
        case 14: return USER_GUIDED_FIRST_SOLUTION;
        case 11: return RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP;
        case 12: return RANDOM_VARIABLE_LNS_GUIDED_BY_LP;
        case 16: return RELATION_GRAPH_LNS;
        case 17: return RELATION_GRAPH_LNS_GUIDED_BY_LP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OptimizerType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OptimizerType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OptimizerType>() {
            public OptimizerType findValueByNumber(int number) {
              return OptimizerType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.ortools.bop.BopOptimizerMethod.getDescriptor().getEnumTypes().get(0);
    }

    private static final OptimizerType[] VALUES = values();

    public static OptimizerType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OptimizerType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:operations_research.bop.BopOptimizerMethod.OptimizerType)
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>optional .operations_research.bop.BopOptimizerMethod.OptimizerType type = 1;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override public boolean hasType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .operations_research.bop.BopOptimizerMethod.OptimizerType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.google.ortools.bop.BopOptimizerMethod.OptimizerType getType() {
    com.google.ortools.bop.BopOptimizerMethod.OptimizerType result = com.google.ortools.bop.BopOptimizerMethod.OptimizerType.forNumber(type_);
    return result == null ? com.google.ortools.bop.BopOptimizerMethod.OptimizerType.SAT_CORE_BASED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, type_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ortools.bop.BopOptimizerMethod)) {
      return super.equals(obj);
    }
    com.google.ortools.bop.BopOptimizerMethod other = (com.google.ortools.bop.BopOptimizerMethod) obj;

    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (type_ != other.type_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.ortools.bop.BopOptimizerMethod parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.ortools.bop.BopOptimizerMethod parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ortools.bop.BopOptimizerMethod parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ortools.bop.BopOptimizerMethod prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Method used to optimize a solution in Bop.
   *
   * NEXT TAG: 16
   * </pre>
   *
   * Protobuf type {@code operations_research.bop.BopOptimizerMethod}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:operations_research.bop.BopOptimizerMethod)
      com.google.ortools.bop.BopOptimizerMethodOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ortools.bop.BopParametersOuterClass.internal_static_operations_research_bop_BopOptimizerMethod_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ortools.bop.BopParametersOuterClass.internal_static_operations_research_bop_BopOptimizerMethod_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ortools.bop.BopOptimizerMethod.class, com.google.ortools.bop.BopOptimizerMethod.Builder.class);
    }

    // Construct using com.google.ortools.bop.BopOptimizerMethod.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ortools.bop.BopParametersOuterClass.internal_static_operations_research_bop_BopOptimizerMethod_descriptor;
    }

    @java.lang.Override
    public com.google.ortools.bop.BopOptimizerMethod getDefaultInstanceForType() {
      return com.google.ortools.bop.BopOptimizerMethod.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ortools.bop.BopOptimizerMethod build() {
      com.google.ortools.bop.BopOptimizerMethod result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ortools.bop.BopOptimizerMethod buildPartial() {
      com.google.ortools.bop.BopOptimizerMethod result = new com.google.ortools.bop.BopOptimizerMethod(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.ortools.bop.BopOptimizerMethod result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ortools.bop.BopOptimizerMethod) {
        return mergeFrom((com.google.ortools.bop.BopOptimizerMethod)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ortools.bop.BopOptimizerMethod other) {
      if (other == com.google.ortools.bop.BopOptimizerMethod.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              com.google.ortools.bop.BopOptimizerMethod.OptimizerType tmpValue =
                  com.google.ortools.bop.BopOptimizerMethod.OptimizerType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                type_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>optional .operations_research.bop.BopOptimizerMethod.OptimizerType type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .operations_research.bop.BopOptimizerMethod.OptimizerType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.google.ortools.bop.BopOptimizerMethod.OptimizerType getType() {
      com.google.ortools.bop.BopOptimizerMethod.OptimizerType result = com.google.ortools.bop.BopOptimizerMethod.OptimizerType.forNumber(type_);
      return result == null ? com.google.ortools.bop.BopOptimizerMethod.OptimizerType.SAT_CORE_BASED : result;
    }
    /**
     * <code>optional .operations_research.bop.BopOptimizerMethod.OptimizerType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.google.ortools.bop.BopOptimizerMethod.OptimizerType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .operations_research.bop.BopOptimizerMethod.OptimizerType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:operations_research.bop.BopOptimizerMethod)
  }

  // @@protoc_insertion_point(class_scope:operations_research.bop.BopOptimizerMethod)
  private static final com.google.ortools.bop.BopOptimizerMethod DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ortools.bop.BopOptimizerMethod();
  }

  public static com.google.ortools.bop.BopOptimizerMethod getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BopOptimizerMethod>
      PARSER = new com.google.protobuf.AbstractParser<BopOptimizerMethod>() {
    @java.lang.Override
    public BopOptimizerMethod parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BopOptimizerMethod> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BopOptimizerMethod> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ortools.bop.BopOptimizerMethod getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

