/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

/**
 *  A BaseObject is the root of all reversibly allocated objects.<br>
 *  A DebugString method and the associated &lt;< operator are implemented<br>
 *  as a convenience.
 */
public class BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BaseObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BaseObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(BaseObject obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_BaseObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BaseObject() {
    this(mainJNI.new_BaseObject(), true);
  }

  public String toString() {
    return mainJNI.BaseObject_toString(swigCPtr, this);
  }

}
