// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/search_stats.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.constraintsolver;

public interface ConstraintSolverStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.ConstraintSolverStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of branches explored.
   * </pre>
   *
   * <code>int64 num_branches = 1;</code>
   * @return The numBranches.
   */
  long getNumBranches();

  /**
   * <pre>
   * Number of failures/backtracks.
   * </pre>
   *
   * <code>int64 num_failures = 2;</code>
   * @return The numFailures.
   */
  long getNumFailures();

  /**
   * <pre>
   * Number of solutions found.
   * </pre>
   *
   * <code>int64 num_solutions = 3;</code>
   * @return The numSolutions.
   */
  long getNumSolutions();

  /**
   * <pre>
   * Memory usage of the solver.
   * </pre>
   *
   * <code>int64 bytes_used = 4;</code>
   * @return The bytesUsed.
   */
  long getBytesUsed();

  /**
   * <pre>
   * Total time spent in the solver.
   * </pre>
   *
   * <code>double duration_seconds = 5;</code>
   * @return The durationSeconds.
   */
  double getDurationSeconds();
}
