/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class IntBoolPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntBoolPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntBoolPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IntBoolPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_IntBoolPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntBoolPair() {
    this(mainJNI.new_IntBoolPair__SWIG_0(), true);
  }

  public IntBoolPair(int first, boolean second) {
    this(mainJNI.new_IntBoolPair__SWIG_1(first, second), true);
  }

  public IntBoolPair(IntBoolPair other) {
    this(mainJNI.new_IntBoolPair__SWIG_2(IntBoolPair.getCPtr(other), other), true);
  }

  public void setFirst(int value) {
    mainJNI.IntBoolPair_first_set(swigCPtr, this, value);
  }

  public int getFirst() {
    return mainJNI.IntBoolPair_first_get(swigCPtr, this);
  }

  public void setSecond(boolean value) {
    mainJNI.IntBoolPair_second_set(swigCPtr, this, value);
  }

  public boolean getSecond() {
    return mainJNI.IntBoolPair_second_get(swigCPtr, this);
  }

}
