/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

/**
 *  The class Iterator has two direct subclasses. HoleIterators<br>
 *  iterates over all holes, that is value removed between the<br>
 *  current min and max of the variable since the last time the<br>
 *  variable was processed in the queue. DomainIterators iterates<br>
 *  over all elements of the variable domain. Both iterators are not<br>
 *  robust to domain changes. Hole iterators can also report values outside<br>
 *  the current min and max of the variable.<br>
 *  HoleIterators should only be called from a demon attached to the<br>
 *  variable that has created this iterator.<br>
 *  IntVar* current_var;<br>
 *  std::unique_ptr&lt;IntVarIterator&gt; it(current_var-&gt;MakeHoleIterator(false));<br>
 *  for (const int64_t hole : InitAndGetValues(it)) {<br>
 * use the hole<br>
 *  }
 */
public class IntVarIterator extends BaseObject {
  private transient long swigCPtr;

  protected IntVarIterator(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.IntVarIterator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVarIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IntVarIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_IntVarIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  This method must be called before each loop.
   */
  public void init() {
    mainJNI.IntVarIterator_init(swigCPtr, this);
  }

  /**
   *  This method indicates if we can call Value() or not.
   */
  public boolean ok() {
    return mainJNI.IntVarIterator_ok(swigCPtr, this);
  }

  /**
   *  This method returns the current value of the iterator.
   */
  public long value() {
    return mainJNI.IntVarIterator_value(swigCPtr, this);
  }

  /**
   *  This method moves the iterator to the next value.
   */
  public void next() {
    mainJNI.IntVarIterator_next(swigCPtr, this);
  }

  /**
   *  Pretty Print.
   */
  public String toString() {
    return mainJNI.IntVarIterator_toString(swigCPtr, this);
  }

}
