// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/search_stats.proto

// Protobuf Java Version: 4.26.1
package com.google.ortools.constraintsolver;

public interface LocalSearchStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.LocalSearchStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Statistics for each first solution called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.FirstSolutionStatistics first_solution_statistics = 6;</code>
   */
  java.util.List<com.google.ortools.constraintsolver.LocalSearchStatistics.FirstSolutionStatistics> 
      getFirstSolutionStatisticsList();
  /**
   * <pre>
   * Statistics for each first solution called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.FirstSolutionStatistics first_solution_statistics = 6;</code>
   */
  com.google.ortools.constraintsolver.LocalSearchStatistics.FirstSolutionStatistics getFirstSolutionStatistics(int index);
  /**
   * <pre>
   * Statistics for each first solution called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.FirstSolutionStatistics first_solution_statistics = 6;</code>
   */
  int getFirstSolutionStatisticsCount();
  /**
   * <pre>
   * Statistics for each first solution called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.FirstSolutionStatistics first_solution_statistics = 6;</code>
   */
  java.util.List<? extends com.google.ortools.constraintsolver.LocalSearchStatistics.FirstSolutionStatisticsOrBuilder> 
      getFirstSolutionStatisticsOrBuilderList();
  /**
   * <pre>
   * Statistics for each first solution called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.FirstSolutionStatistics first_solution_statistics = 6;</code>
   */
  com.google.ortools.constraintsolver.LocalSearchStatistics.FirstSolutionStatisticsOrBuilder getFirstSolutionStatisticsOrBuilder(
      int index);

  /**
   * <pre>
   * Statistics for each operator called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics local_search_operator_statistics = 1;</code>
   */
  java.util.List<com.google.ortools.constraintsolver.LocalSearchStatistics.LocalSearchOperatorStatistics> 
      getLocalSearchOperatorStatisticsList();
  /**
   * <pre>
   * Statistics for each operator called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics local_search_operator_statistics = 1;</code>
   */
  com.google.ortools.constraintsolver.LocalSearchStatistics.LocalSearchOperatorStatistics getLocalSearchOperatorStatistics(int index);
  /**
   * <pre>
   * Statistics for each operator called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics local_search_operator_statistics = 1;</code>
   */
  int getLocalSearchOperatorStatisticsCount();
  /**
   * <pre>
   * Statistics for each operator called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics local_search_operator_statistics = 1;</code>
   */
  java.util.List<? extends com.google.ortools.constraintsolver.LocalSearchStatistics.LocalSearchOperatorStatisticsOrBuilder> 
      getLocalSearchOperatorStatisticsOrBuilderList();
  /**
   * <pre>
   * Statistics for each operator called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics local_search_operator_statistics = 1;</code>
   */
  com.google.ortools.constraintsolver.LocalSearchStatistics.LocalSearchOperatorStatisticsOrBuilder getLocalSearchOperatorStatisticsOrBuilder(
      int index);

  /**
   * <pre>
   * Total number of (filtered/accepted) neighbors created during the search.
   * </pre>
   *
   * <code>int64 total_num_neighbors = 3;</code>
   * @return The totalNumNeighbors.
   */
  long getTotalNumNeighbors();

  /**
   * <code>int64 total_num_filtered_neighbors = 4;</code>
   * @return The totalNumFilteredNeighbors.
   */
  long getTotalNumFilteredNeighbors();

  /**
   * <code>int64 total_num_accepted_neighbors = 5;</code>
   * @return The totalNumAcceptedNeighbors.
   */
  long getTotalNumAcceptedNeighbors();

  /**
   * <pre>
   * Statistics for each filter called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchFilterStatistics local_search_filter_statistics = 2;</code>
   */
  java.util.List<com.google.ortools.constraintsolver.LocalSearchStatistics.LocalSearchFilterStatistics> 
      getLocalSearchFilterStatisticsList();
  /**
   * <pre>
   * Statistics for each filter called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchFilterStatistics local_search_filter_statistics = 2;</code>
   */
  com.google.ortools.constraintsolver.LocalSearchStatistics.LocalSearchFilterStatistics getLocalSearchFilterStatistics(int index);
  /**
   * <pre>
   * Statistics for each filter called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchFilterStatistics local_search_filter_statistics = 2;</code>
   */
  int getLocalSearchFilterStatisticsCount();
  /**
   * <pre>
   * Statistics for each filter called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchFilterStatistics local_search_filter_statistics = 2;</code>
   */
  java.util.List<? extends com.google.ortools.constraintsolver.LocalSearchStatistics.LocalSearchFilterStatisticsOrBuilder> 
      getLocalSearchFilterStatisticsOrBuilderList();
  /**
   * <pre>
   * Statistics for each filter called during the search.
   * </pre>
   *
   * <code>repeated .operations_research.LocalSearchStatistics.LocalSearchFilterStatistics local_search_filter_statistics = 2;</code>
   */
  com.google.ortools.constraintsolver.LocalSearchStatistics.LocalSearchFilterStatisticsOrBuilder getLocalSearchFilterStatisticsOrBuilder(
      int index);
}
