/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class LocalSearchOperatorState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LocalSearchOperatorState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LocalSearchOperatorState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LocalSearchOperatorState obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_LocalSearchOperatorState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LocalSearchOperatorState() {
    this(mainJNI.new_LocalSearchOperatorState(), true);
  }

  public void SetCurrentDomainInjectiveAndKeepInverseValues(int max_value) {
    mainJNI.LocalSearchOperatorState_SetCurrentDomainInjectiveAndKeepInverseValues(swigCPtr, this, max_value);
  }

  /**
   *  Returns the value in the current assignment of the variable of given<br>
   *  index.
   */
  public long CandidateValue(long index) {
    return mainJNI.LocalSearchOperatorState_CandidateValue(swigCPtr, this, index);
  }

  public long CommittedValue(long index) {
    return mainJNI.LocalSearchOperatorState_CommittedValue(swigCPtr, this, index);
  }

  public long CheckPointValue(long index) {
    return mainJNI.LocalSearchOperatorState_CheckPointValue(swigCPtr, this, index);
  }

  public void SetCandidateValue(long index, long value) {
    mainJNI.LocalSearchOperatorState_SetCandidateValue(swigCPtr, this, index, value);
  }

  public boolean CandidateIsActive(long index) {
    return mainJNI.LocalSearchOperatorState_CandidateIsActive(swigCPtr, this, index);
  }

  public void SetCandidateActive(long index, boolean active) {
    mainJNI.LocalSearchOperatorState_SetCandidateActive(swigCPtr, this, index, active);
  }

  public void Commit() {
    mainJNI.LocalSearchOperatorState_Commit(swigCPtr, this);
  }

  public void CheckPoint() {
    mainJNI.LocalSearchOperatorState_CheckPoint(swigCPtr, this);
  }

  public void Revert(boolean only_incremental) {
    mainJNI.LocalSearchOperatorState_Revert(swigCPtr, this, only_incremental);
  }

  public long[] CandidateIndicesChanged() {
  return mainJNI.LocalSearchOperatorState_CandidateIndicesChanged(swigCPtr, this);
}

  public long[] IncrementalIndicesChanged() {
  return mainJNI.LocalSearchOperatorState_IncrementalIndicesChanged(swigCPtr, this);
}

  public void Resize(int size) {
    mainJNI.LocalSearchOperatorState_Resize(swigCPtr, this, size);
  }

  public long CandidateInverseValue(long value) {
    return mainJNI.LocalSearchOperatorState_CandidateInverseValue(swigCPtr, this, value);
  }

  public long CommittedInverseValue(long value) {
    return mainJNI.LocalSearchOperatorState_CommittedInverseValue(swigCPtr, this, value);
  }

}
