/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class ObjectiveMonitor extends SearchMonitor {
  private transient long swigCPtr;

  protected ObjectiveMonitor(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.ObjectiveMonitor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectiveMonitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ObjectiveMonitor obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_ObjectiveMonitor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ObjectiveMonitor(Solver solver, SWIGTYPE_p_std__vectorT_bool_t maximize, IntVar[] vars, long[] steps) {
    this(mainJNI.new_ObjectiveMonitor(Solver.getCPtr(solver), solver, SWIGTYPE_p_std__vectorT_bool_t.getCPtr(maximize), vars, steps), true);
  }

  public IntVar ObjectiveVar(int index) {
    long cPtr = mainJNI.ObjectiveMonitor_ObjectiveVar(swigCPtr, this, index);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public IntVar MinimizationVar(int index) {
    long cPtr = mainJNI.ObjectiveMonitor_MinimizationVar(swigCPtr, this, index);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public long Step(int index) {
    return mainJNI.ObjectiveMonitor_Step(swigCPtr, this, index);
  }

  public boolean Maximize(int index) {
    return mainJNI.ObjectiveMonitor_Maximize(swigCPtr, this, index);
  }

  public long BestValue(int index) {
    return mainJNI.ObjectiveMonitor_BestValue(swigCPtr, this, index);
  }

  public int Size() {
    return mainJNI.ObjectiveMonitor_Size(swigCPtr, this);
  }

  public void enterSearch() {
    mainJNI.ObjectiveMonitor_enterSearch(swigCPtr, this);
  }

  public boolean atSolution() {
    return mainJNI.ObjectiveMonitor_atSolution(swigCPtr, this);
  }

  public boolean acceptDelta(Assignment delta, Assignment deltadelta) {
    return mainJNI.ObjectiveMonitor_acceptDelta(swigCPtr, this, Assignment.getCPtr(delta), delta, Assignment.getCPtr(deltadelta), deltadelta);
  }

  public void accept(ModelVisitor visitor) {
    mainJNI.ObjectiveMonitor_accept(swigCPtr, this, ModelVisitor.getCPtr(visitor), visitor);
  }

}
