// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/routing_parameters.proto
// Protobuf Java Version: 4.26.1

package com.google.ortools.constraintsolver;

public final class RoutingParameters {
  private RoutingParameters() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RoutingParameters.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingSearchParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_operations_research_RoutingSearchParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingSearchParameters_ImprovementSearchLimitParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_operations_research_RoutingSearchParameters_ImprovementSearchLimitParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingModelParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_operations_research_RoutingModelParameters_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2ortools/constraint_solver/routing_para" +
      "meters.proto\022\023operations_research\032\036googl" +
      "e/protobuf/duration.proto\032-ortools/const" +
      "raint_solver/routing_enums.proto\032+ortool" +
      "s/constraint_solver/routing_ils.proto\0321o" +
      "rtools/constraint_solver/solver_paramete" +
      "rs.proto\032 ortools/sat/sat_parameters.pro" +
      "to\032#ortools/util/optional_boolean.proto\"" +
      "\270.\n\027RoutingSearchParameters\022Q\n\027first_sol" +
      "ution_strategy\030\001 \001(\01620.operations_resear" +
      "ch.FirstSolutionStrategy.Value\022.\n&use_un" +
      "filtered_first_solution_strategy\030\002 \001(\010\022\037" +
      "\n\027savings_neighbors_ratio\030\016 \001(\001\022&\n\036savin" +
      "gs_max_memory_usage_bytes\030\027 \001(\001\022 \n\030savin" +
      "gs_add_reverse_arcs\030\017 \001(\010\022\037\n\027savings_arc" +
      "_coefficient\030\022 \001(\001\022\037\n\027savings_parallel_r" +
      "outes\030\023 \001(\010\022/\n\'cheapest_insertion_farthe" +
      "st_seeds_ratio\030\020 \001(\001\0229\n1cheapest_inserti" +
      "on_first_solution_neighbors_ratio\030\025 \001(\001\022" +
      "7\n/cheapest_insertion_first_solution_min" +
      "_neighbors\030, \001(\005\0226\n.cheapest_insertion_l" +
      "s_operator_neighbors_ratio\030\037 \001(\001\0224\n,chea" +
      "pest_insertion_ls_operator_min_neighbors" +
      "\030- \001(\005\022P\nHcheapest_insertion_first_solut" +
      "ion_use_neighbors_ratio_for_initializati" +
      "on\030. \001(\010\0222\n*cheapest_insertion_add_unper" +
      "formed_entries\030( \001(\010\022}\n1local_cheapest_i" +
      "nsertion_pickup_delivery_strategy\0301 \001(\0162" +
      "B.operations_research.RoutingSearchParam" +
      "eters.PairInsertionStrategy\022\202\001\n6local_ch" +
      "eapest_cost_insertion_pickup_delivery_st" +
      "rategy\0307 \001(\0162B.operations_research.Routi" +
      "ngSearchParameters.PairInsertionStrategy" +
      "\022)\n!christofides_use_minimum_matching\030\036 " +
      "\001(\010\022*\n\"first_solution_optimization_perio" +
      "d\030; \001(\005\022m\n\026local_search_operators\030\003 \001(\0132" +
      "M.operations_research.RoutingSearchParam" +
      "eters.LocalSearchNeighborhoodOperators\022#" +
      "\n\033ls_operator_neighbors_ratio\0305 \001(\001\022!\n\031l" +
      "s_operator_min_neighbors\0306 \001(\005\0224\n,use_mu" +
      "lti_armed_bandit_concatenate_operators\030)" +
      " \001(\010\022?\n7multi_armed_bandit_compound_oper" +
      "ator_memory_coefficient\030* \001(\001\022D\n<multi_a" +
      "rmed_bandit_compound_operator_exploratio" +
      "n_coefficient\030+ \001(\001\0225\n-relocate_expensiv" +
      "e_chain_num_arcs_to_consider\030\024 \001(\005\022:\n2he" +
      "uristic_expensive_chain_lns_num_arcs_to_" +
      "consider\030  \001(\005\022+\n#heuristic_close_nodes_" +
      "lns_num_nodes\030# \001(\005\022W\n\032local_search_meta" +
      "heuristic\030\004 \001(\01623.operations_research.Lo" +
      "calSearchMetaheuristic.Value\022.\n&guided_l" +
      "ocal_search_lambda_coefficient\030\005 \001(\001\022@\n8" +
      "guided_local_search_reset_penalties_on_n" +
      "ew_best_solution\0303 \001(\010\022\036\n\026use_depth_firs" +
      "t_search\030\006 \001(\010\0224\n\006use_cp\030\034 \001(\0162$.operati" +
      "ons_research.OptionalBoolean\0228\n\nuse_cp_s" +
      "at\030\033 \001(\0162$.operations_research.OptionalB" +
      "oolean\022D\n\026use_generalized_cp_sat\030/ \001(\0162$" +
      ".operations_research.OptionalBoolean\022>\n\016" +
      "sat_parameters\0300 \001(\0132&.operations_resear" +
      "ch.sat.SatParameters\022,\n$report_intermedi" +
      "ate_cp_sat_solutions\0308 \001(\010\022)\n!fallback_t" +
      "o_cp_sat_size_threshold\0304 \001(\005\022c\n\034continu" +
      "ous_scheduling_solver\030! \001(\0162=.operations" +
      "_research.RoutingSearchParameters.Schedu" +
      "lingSolver\022f\n\037mixed_integer_scheduling_s" +
      "olver\030\" \001(\0162=.operations_research.Routin" +
      "gSearchParameters.SchedulingSolver\022C\n6di" +
      "sable_scheduling_beware_this_may_degrade" +
      "_performance\0302 \001(\010H\000\210\001\001\022\031\n\021optimization_" +
      "step\030\007 \001(\001\022&\n\036number_of_solutions_to_col" +
      "lect\030\021 \001(\005\022\026\n\016solution_limit\030\010 \001(\003\022-\n\nti" +
      "me_limit\030\t \001(\0132\031.google.protobuf.Duratio" +
      "n\0221\n\016lns_time_limit\030\n \001(\0132\031.google.proto" +
      "buf.Duration\022%\n\035secondary_ls_time_limit_" +
      "ratio\0309 \001(\001\022s\n\034improvement_limit_paramet" +
      "ers\030% \001(\0132M.operations_research.RoutingS" +
      "earchParameters.ImprovementSearchLimitPa" +
      "rameters\022\034\n\024use_full_propagation\030\013 \001(\010\022\022" +
      "\n\nlog_search\030\r \001(\010\022\037\n\027log_cost_scaling_f" +
      "actor\030\026 \001(\001\022\027\n\017log_cost_offset\030\035 \001(\001\022\017\n\007" +
      "log_tag\030$ \001(\t\022!\n\031use_iterated_local_sear" +
      "ch\030: \001(\010\022\\\n iterated_local_search_parame" +
      "ters\030< \001(\01322.operations_research.Iterate" +
      "dLocalSearchParameters\032\244\023\n LocalSearchNe" +
      "ighborhoodOperators\022:\n\014use_relocate\030\001 \001(" +
      "\0162$.operations_research.OptionalBoolean\022" +
      "?\n\021use_relocate_pair\030\002 \001(\0162$.operations_" +
      "research.OptionalBoolean\022E\n\027use_light_re" +
      "locate_pair\030\030 \001(\0162$.operations_research." +
      "OptionalBoolean\022D\n\026use_relocate_neighbor" +
      "s\030\003 \001(\0162$.operations_research.OptionalBo" +
      "olean\022B\n\024use_relocate_subtrip\030\031 \001(\0162$.op" +
      "erations_research.OptionalBoolean\022:\n\014use" +
      "_exchange\030\004 \001(\0162$.operations_research.Op" +
      "tionalBoolean\022?\n\021use_exchange_pair\030\026 \001(\016" +
      "2$.operations_research.OptionalBoolean\022B" +
      "\n\024use_exchange_subtrip\030\032 \001(\0162$.operation" +
      "s_research.OptionalBoolean\0227\n\tuse_cross\030" +
      "\005 \001(\0162$.operations_research.OptionalBool" +
      "ean\022@\n\022use_cross_exchange\030\006 \001(\0162$.operat" +
      "ions_research.OptionalBoolean\022J\n\034use_rel" +
      "ocate_expensive_chain\030\027 \001(\0162$.operations" +
      "_research.OptionalBoolean\0229\n\013use_two_opt" +
      "\030\007 \001(\0162$.operations_research.OptionalBoo" +
      "lean\0228\n\nuse_or_opt\030\010 \001(\0162$.operations_re" +
      "search.OptionalBoolean\022?\n\021use_lin_kernig" +
      "han\030\t \001(\0162$.operations_research.Optional" +
      "Boolean\0229\n\013use_tsp_opt\030\n \001(\0162$.operation" +
      "s_research.OptionalBoolean\022=\n\017use_make_a" +
      "ctive\030\013 \001(\0162$.operations_research.Option" +
      "alBoolean\022J\n\034use_relocate_and_make_activ" +
      "e\030\025 \001(\0162$.operations_research.OptionalBo" +
      "olean\022?\n\021use_make_inactive\030\014 \001(\0162$.opera" +
      "tions_research.OptionalBoolean\022E\n\027use_ma" +
      "ke_chain_inactive\030\r \001(\0162$.operations_res" +
      "earch.OptionalBoolean\022=\n\017use_swap_active" +
      "\030\016 \001(\0162$.operations_research.OptionalBoo" +
      "lean\022F\n\030use_extended_swap_active\030\017 \001(\0162$" +
      ".operations_research.OptionalBoolean\022K\n\035" +
      "use_shortest_path_swap_active\030\" \001(\0162$.op" +
      "erations_research.OptionalBoolean\022G\n\031use" +
      "_node_pair_swap_active\030\024 \001(\0162$.operation" +
      "s_research.OptionalBoolean\022:\n\014use_path_l" +
      "ns\030\020 \001(\0162$.operations_research.OptionalB" +
      "oolean\022?\n\021use_full_path_lns\030\021 \001(\0162$.oper" +
      "ations_research.OptionalBoolean\0229\n\013use_t" +
      "sp_lns\030\022 \001(\0162$.operations_research.Optio" +
      "nalBoolean\022>\n\020use_inactive_lns\030\023 \001(\0162$.o" +
      "perations_research.OptionalBoolean\022T\n&us" +
      "e_global_cheapest_insertion_path_lns\030\033 \001" +
      "(\0162$.operations_research.OptionalBoolean" +
      "\022S\n%use_local_cheapest_insertion_path_ln" +
      "s\030\034 \001(\0162$.operations_research.OptionalBo" +
      "olean\022l\n>use_relocate_path_global_cheape" +
      "st_insertion_insert_unperformed\030! \001(\0162$." +
      "operations_research.OptionalBoolean\022_\n1u" +
      "se_global_cheapest_insertion_expensive_c" +
      "hain_lns\030\035 \001(\0162$.operations_research.Opt" +
      "ionalBoolean\022^\n0use_local_cheapest_inser" +
      "tion_expensive_chain_lns\030\036 \001(\0162$.operati" +
      "ons_research.OptionalBoolean\022[\n-use_glob" +
      "al_cheapest_insertion_close_nodes_lns\030\037 " +
      "\001(\0162$.operations_research.OptionalBoolea" +
      "n\022Z\n,use_local_cheapest_insertion_close_" +
      "nodes_lns\030  \001(\0162$.operations_research.Op" +
      "tionalBoolean\032u\n ImprovementSearchLimitP" +
      "arameters\022$\n\034improvement_rate_coefficien" +
      "t\030& \001(\001\022+\n#improvement_rate_solutions_di" +
      "stance\030\' \001(\005\"\222\001\n\025PairInsertionStrategy\022\r" +
      "\n\tAUTOMATIC\020\000\022\"\n\036BEST_PICKUP_THEN_BEST_D" +
      "ELIVERY\020\001\022\035\n\031BEST_PICKUP_DELIVERY_PAIR\020\002" +
      "\022\'\n#BEST_PICKUP_DELIVERY_PAIR_MULTITOUR\020" +
      "\003\"T\n\020SchedulingSolver\022\024\n\020SCHEDULING_UNSE" +
      "T\020\000\022\023\n\017SCHEDULING_GLOP\020\001\022\025\n\021SCHEDULING_C" +
      "P_SAT\020\002B9\n7_disable_scheduling_beware_th" +
      "is_may_degrade_performance\"\250\001\n\026RoutingMo" +
      "delParameters\022J\n\021solver_parameters\030\001 \001(\013" +
      "2/.operations_research.ConstraintSolverP" +
      "arameters\022!\n\031reduce_vehicle_cost_model\030\002" +
      " \001(\010\022\037\n\027max_callback_cache_size\030\003 \001(\005BI\n" +
      "#com.google.ortools.constraintsolverP\001\252\002" +
      "\037Google.OrTools.ConstraintSolverb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.ortools.constraintsolver.RoutingEnums.getDescriptor(),
          operations_research.RoutingIls.getDescriptor(),
          com.google.ortools.constraintsolver.SolverParameters.getDescriptor(),
          com.google.ortools.sat.SatParametersOuterClass.getDescriptor(),
          com.google.ortools.util.OptionalBooleanOuterClass.getDescriptor(),
        });
    internal_static_operations_research_RoutingSearchParameters_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_operations_research_RoutingSearchParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_operations_research_RoutingSearchParameters_descriptor,
        new java.lang.String[] { "FirstSolutionStrategy", "UseUnfilteredFirstSolutionStrategy", "SavingsNeighborsRatio", "SavingsMaxMemoryUsageBytes", "SavingsAddReverseArcs", "SavingsArcCoefficient", "SavingsParallelRoutes", "CheapestInsertionFarthestSeedsRatio", "CheapestInsertionFirstSolutionNeighborsRatio", "CheapestInsertionFirstSolutionMinNeighbors", "CheapestInsertionLsOperatorNeighborsRatio", "CheapestInsertionLsOperatorMinNeighbors", "CheapestInsertionFirstSolutionUseNeighborsRatioForInitialization", "CheapestInsertionAddUnperformedEntries", "LocalCheapestInsertionPickupDeliveryStrategy", "LocalCheapestCostInsertionPickupDeliveryStrategy", "ChristofidesUseMinimumMatching", "FirstSolutionOptimizationPeriod", "LocalSearchOperators", "LsOperatorNeighborsRatio", "LsOperatorMinNeighbors", "UseMultiArmedBanditConcatenateOperators", "MultiArmedBanditCompoundOperatorMemoryCoefficient", "MultiArmedBanditCompoundOperatorExplorationCoefficient", "RelocateExpensiveChainNumArcsToConsider", "HeuristicExpensiveChainLnsNumArcsToConsider", "HeuristicCloseNodesLnsNumNodes", "LocalSearchMetaheuristic", "GuidedLocalSearchLambdaCoefficient", "GuidedLocalSearchResetPenaltiesOnNewBestSolution", "UseDepthFirstSearch", "UseCp", "UseCpSat", "UseGeneralizedCpSat", "SatParameters", "ReportIntermediateCpSatSolutions", "FallbackToCpSatSizeThreshold", "ContinuousSchedulingSolver", "MixedIntegerSchedulingSolver", "DisableSchedulingBewareThisMayDegradePerformance", "OptimizationStep", "NumberOfSolutionsToCollect", "SolutionLimit", "TimeLimit", "LnsTimeLimit", "SecondaryLsTimeLimitRatio", "ImprovementLimitParameters", "UseFullPropagation", "LogSearch", "LogCostScalingFactor", "LogCostOffset", "LogTag", "UseIteratedLocalSearch", "IteratedLocalSearchParameters", });
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor =
      internal_static_operations_research_RoutingSearchParameters_descriptor.getNestedTypes().get(0);
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor,
        new java.lang.String[] { "UseRelocate", "UseRelocatePair", "UseLightRelocatePair", "UseRelocateNeighbors", "UseRelocateSubtrip", "UseExchange", "UseExchangePair", "UseExchangeSubtrip", "UseCross", "UseCrossExchange", "UseRelocateExpensiveChain", "UseTwoOpt", "UseOrOpt", "UseLinKernighan", "UseTspOpt", "UseMakeActive", "UseRelocateAndMakeActive", "UseMakeInactive", "UseMakeChainInactive", "UseSwapActive", "UseExtendedSwapActive", "UseShortestPathSwapActive", "UseNodePairSwapActive", "UsePathLns", "UseFullPathLns", "UseTspLns", "UseInactiveLns", "UseGlobalCheapestInsertionPathLns", "UseLocalCheapestInsertionPathLns", "UseRelocatePathGlobalCheapestInsertionInsertUnperformed", "UseGlobalCheapestInsertionExpensiveChainLns", "UseLocalCheapestInsertionExpensiveChainLns", "UseGlobalCheapestInsertionCloseNodesLns", "UseLocalCheapestInsertionCloseNodesLns", });
    internal_static_operations_research_RoutingSearchParameters_ImprovementSearchLimitParameters_descriptor =
      internal_static_operations_research_RoutingSearchParameters_descriptor.getNestedTypes().get(1);
    internal_static_operations_research_RoutingSearchParameters_ImprovementSearchLimitParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_operations_research_RoutingSearchParameters_ImprovementSearchLimitParameters_descriptor,
        new java.lang.String[] { "ImprovementRateCoefficient", "ImprovementRateSolutionsDistance", });
    internal_static_operations_research_RoutingModelParameters_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_operations_research_RoutingModelParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_operations_research_RoutingModelParameters_descriptor,
        new java.lang.String[] { "SolverParameters", "ReduceVehicleCostModel", "MaxCallbackCacheSize", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.ortools.constraintsolver.RoutingEnums.getDescriptor();
    operations_research.RoutingIls.getDescriptor();
    com.google.ortools.constraintsolver.SolverParameters.getDescriptor();
    com.google.ortools.sat.SatParametersOuterClass.getDescriptor();
    com.google.ortools.util.OptionalBooleanOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
